-- Remove document_templates table (not used - documents generated by Python service)
-- Target: Yandex Cloud self-hosted Supabase instance (supabase.service-mk.ru)
DROP TABLE IF EXISTS document_templates CASCADE;






