// Mock data for the CRM application
import type { Client, JobTemplate, Order, JobPreset, CompanySettings, DocumentTemplate } from './types';

export const mockClients: Client[] = [
  {
    id: 'client-1',
    name: 'John Anderson',
    company: 'Anderson Manufacturing',
    phone: '(555) 123-4567',
    email: 'john@andersonmfg.com',
    address: '1234 Industrial Blvd, Detroit, MI 48201',
    inn: '38-1234567',
    notes: 'Preferred customer - always pays on time',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'client-2',
    name: 'Sarah Martinez',
    company: 'Metro Steel Works',
    phone: '(555) 234-5678',
    email: 'sarah@metrosteel.com',
    address: '5678 Factory Ave, Cleveland, OH 44101',
    inn: '39-2345678',
    notes: 'Requires detailed invoices',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-10-28'),
  },
  {
    id: 'client-3',
    name: 'Michael Chen',
    company: 'Chen Fabrication LLC',
    phone: '(555) 345-6789',
    email: 'michael@chenfab.com',
    address: '9012 Workshop Dr, Pittsburgh, PA 15201',
    inn: '40-3456789',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-11-05'),
  },
  {
    id: 'client-4',
    name: 'Jennifer Wilson',
    company: 'Wilson Industrial Services',
    phone: '(555) 456-7890',
    email: 'jen@wilsonind.com',
    address: '3456 Commerce St, Buffalo, NY 14201',
    inn: '41-4567890',
    notes: 'Large volume orders - monthly billing',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-11-03'),
  },
  {
    id: 'client-5',
    name: 'Robert Taylor',
    company: 'Taylor Construction',
    phone: '(555) 567-8901',
    email: 'robert@taylorconstruct.com',
    address: '7890 Builder Ln, Rochester, NY 14602',
    createdAt: new Date('2024-05-12'),
    updatedAt: new Date('2024-10-30'),
  },
  // Clients imported from XML database
  {
    id: 'client-xml-10001',
    name: 'Куковякин Дмитрий Николаевич',
    company: 'ООО "Вторчермет НЛМК Центр"',
    phone: '',
    email: '',
    address: '141006, Московская обл., гор. округ Мытищи, Мытищи, проезд 4530, 4А, стр. 1',
    inn: '5029129990',
    kpp: '502901001',
    ogrn: '1095029007798',
    bank: {
      name: 'Уральский банк ОАО "Сбербанка России"',
      accountNumber: '40702810316540013439',
      correspondentAccount: '30101810500000000674',
      bik: '046577674',
    },
    notes: 'Постоянный клиент',
    createdAt: new Date('2016-01-18T22:45:00'),
  },
  {
    id: 'client-xml-10004',
    name: 'Тестов Тест Тестович',
    company: '"Заинтересованным лицам"',
    phone: '+7(999)9999999',
    email: 'test@test.te',
    address: '',
    inn: '123456789123',
    notes: 'Additional contact: Мюнц Владимир Константинович (+7(903)2221694, munz1@ya.ru)',
    createdAt: new Date('2016-02-01T19:59:00'),
  },
  {
    id: 'client-xml-10008',
    name: 'Меркулов Евгений Сергеевич',
    company: 'ООО "Промтехносеть"',
    phone: '',
    email: '',
    address: '142155, Московская обл., п. Львовский, пр-д Металургов, д. 3',
    inn: '5036048380',
    kpp: '507401001',
    bank: {
      name: 'Уральский банк ОАО "Сбербанка России"',
      accountNumber: '40702810316540013439',
      correspondentAccount: '30101810500000000674',
      bik: '046577674',
    },
    notes: 'Сергей Семенович',
    createdAt: new Date('2016-02-01T21:27:00'),
  },
];

export const mockJobTemplates: JobTemplate[] = [
  {
    id: 'job-1',
    name: 'MIG Welding - Steel',
    description: 'Metal Inert Gas welding for steel components',
    category: 'Welding',
    unitPrice: 85.00,
    unitOfMeasure: 'hour',
    defaultTax: true,
    lastUpdated: new Date('2024-09-15'),
  },
  {
    id: 'job-2',
    name: 'TIG Welding - Aluminum',
    description: 'Tungsten Inert Gas welding for aluminum parts',
    category: 'Welding',
    unitPrice: 110.00,
    unitOfMeasure: 'hour',
    defaultTax: true,
    lastUpdated: new Date('2024-09-20'),
  },
  {
    id: 'job-3',
    name: 'Steel Cutting',
    description: 'Precision steel cutting and preparation',
    category: 'Fabrication',
    unitPrice: 65.00,
    unitOfMeasure: 'hour',
    defaultTax: true,
    lastUpdated: new Date('2024-08-10'),
  },
  {
    id: 'job-4',
    name: 'Metal Grinding',
    description: 'Surface preparation and finishing',
    category: 'Finishing',
    unitPrice: 55.00,
    unitOfMeasure: 'hour',
    defaultTax: true,
    lastUpdated: new Date('2024-08-15'),
  },
  {
    id: 'job-5',
    name: 'Pipe Welding',
    description: 'Certified pipe welding services',
    category: 'Welding',
    unitPrice: 95.00,
    unitOfMeasure: 'hour',
    defaultTax: true,
    lastUpdated: new Date('2024-10-01'),
  },
  {
    id: 'job-6',
    name: 'Frame Fabrication',
    description: 'Custom metal frame construction',
    category: 'Fabrication',
    unitPrice: 120.00,
    unitOfMeasure: 'unit',
    defaultTax: true,
    lastUpdated: new Date('2024-10-05'),
  },
  {
    id: 'job-7',
    name: 'Bracket Manufacturing',
    description: 'Custom metal bracket production',
    category: 'Fabrication',
    unitPrice: 45.00,
    unitOfMeasure: 'unit',
    defaultTax: true,
    lastUpdated: new Date('2024-09-25'),
  },
  {
    id: 'job-8',
    name: 'Powder Coating',
    description: 'Professional powder coating finish',
    category: 'Finishing',
    unitPrice: 75.00,
    unitOfMeasure: 'unit',
    defaultTax: true,
    lastUpdated: new Date('2024-10-10'),
  },
  {
    id: 'job-9',
    name: 'Metal Polishing',
    description: 'High-quality metal polishing and buffing',
    category: 'Finishing',
    unitPrice: 60.00,
    unitOfMeasure: 'hour',
    defaultTax: true,
    lastUpdated: new Date('2024-09-30'),
  },
  {
    id: 'job-10',
    name: 'Structural Repair',
    description: 'Structural metal repair and reinforcement',
    category: 'Repair',
    unitPrice: 100.00,
    unitOfMeasure: 'hour',
    defaultTax: true,
    lastUpdated: new Date('2024-10-15'),
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-2025-001',
    clientId: 'client-1',
    status: 'in-progress',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-11-05'),
    taxRate: 8.5,
    globalMarkup: 20,
    currency: 'USD',
    orderType: '',
    orderTitle: 'Standard delivery terms apply',
    jobs: [
      {
        id: 'oj-1',
        jobId: 'job-1',
        jobName: 'MIG Welding - Steel',
        description: 'Metal Inert Gas welding for steel components',
        quantity: 8,
        unitPrice: 85.00,
        lineMarkup: 20,
        taxApplicable: true,
        position: 0,
      },
      {
        id: 'oj-2',
        jobId: 'job-4',
        jobName: 'Metal Grinding',
        description: 'Surface preparation and finishing',
        quantity: 4,
        unitPrice: 55.00,
        lineMarkup: 20,
        taxApplicable: true,
        position: 1,
      },
    ],
  },
  {
    id: 'ORD-2025-002',
    clientId: 'client-2',
    status: 'completed',
    createdAt: new Date('2025-10-28'),
    updatedAt: new Date('2025-11-04'),
    taxRate: 8.5,
    globalMarkup: 25,
    currency: 'USD',
    orderType: '',
    orderTitle: '',
    jobs: [
      {
        id: 'oj-3',
        jobId: 'job-2',
        jobName: 'TIG Welding - Aluminum',
        description: 'Tungsten Inert Gas welding for aluminum parts',
        quantity: 12,
        unitPrice: 110.00,
        lineMarkup: 25,
        taxApplicable: true,
        position: 0,
      },
      {
        id: 'oj-4',
        jobId: 'job-8',
        jobName: 'Powder Coating',
        description: 'Professional powder coating finish',
        quantity: 6,
        unitPrice: 75.00,
        lineMarkup: 25,
        taxApplicable: true,
        position: 1,
      },
    ],
  },
  {
    id: 'ORD-2025-003',
    clientId: 'client-3',
    status: 'proposal',
    createdAt: new Date('2025-11-05'),
    updatedAt: new Date('2025-11-05'),
    taxRate: 8.5,
    globalMarkup: 20,
    currency: 'USD',
    orderType: '',
    orderTitle: '',
    jobs: [
      {
        id: 'oj-5',
        jobId: 'job-6',
        jobName: 'Frame Fabrication',
        description: 'Custom metal frame construction',
        quantity: 2,
        unitPrice: 120.00,
        lineMarkup: 20,
        taxApplicable: true,
        position: 0,
      },
    ],
  },
  {
    id: 'ORD-2025-004',
    clientId: 'client-4',
    status: 'in-progress',
    createdAt: new Date('2025-11-03'),
    updatedAt: new Date('2025-11-04'),
    taxRate: 8.5,
    globalMarkup: 22,
    currency: 'USD',
    orderType: '',
    orderTitle: 'Work will commence upon approval',
    jobs: [
      {
        id: 'oj-6',
        jobId: 'job-5',
        jobName: 'Pipe Welding',
        description: 'Certified pipe welding services',
        quantity: 16,
        unitPrice: 95.00,
        lineMarkup: 22,
        taxApplicable: true,
        position: 0,
      },
      {
        id: 'oj-7',
        jobId: 'job-3',
        jobName: 'Steel Cutting',
        description: 'Precision steel cutting and preparation',
        quantity: 8,
        unitPrice: 65.00,
        lineMarkup: 22,
        taxApplicable: true,
        position: 1,
      },
    ],
  },
  {
    id: 'ORD-2025-005',
    clientId: 'client-1',
    status: 'completed',
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2025-10-30'),
    taxRate: 8.5,
    globalMarkup: 20,
    currency: 'USD',
    orderType: '',
    orderTitle: 'Net 30 payment terms',
    jobs: [
      {
        id: 'oj-8',
        jobId: 'job-10',
        jobName: 'Structural Repair',
        description: 'Structural metal repair and reinforcement',
        quantity: 6,
        unitPrice: 100.00,
        lineMarkup: 20,
        taxApplicable: true,
        position: 0,
      },
    ],
  },
  // Orders imported from XML database
  {
    id: 'ORD-XML-20002',
    clientId: 'client-xml-10001',
    status: 'completed',
    createdAt: new Date('2015-11-10T00:00:00'),
    updatedAt: new Date('2015-11-10T23:07:00'),
    taxRate: 8.5,
    globalMarkup: 20,
    currency: 'USD',
    orderType: 'Поставка',
    orderTitle: 'Поставка полумесяцев для шредера',
    jobs: [
      {
        id: 'oj-xml-20002-1',
        jobId: '',
        jobName: 'Изготовление полумесяцев для шредера',
        description: 'Изготовление полумесяцев для шредера',
        quantity: 4,
        unitPrice: 20439.0,
        lineMarkup: 0,
        taxApplicable: true,
        position: 0,
      },
    ],
  },
  {
    id: 'ORD-XML-20003',
    clientId: 'client-xml-10001',
    status: 'completed',
    createdAt: new Date('2015-10-14T00:00:00'),
    updatedAt: new Date('2015-11-17T14:22:00'),
    taxRate: 8.5,
    globalMarkup: 20,
    currency: 'USD',
    orderType: 'Ремонтные работы',
    orderTitle: 'Капитальный ремонт грейфера № L 08. 2 производства Liebherr',
    jobs: [
      {
        id: 'oj-xml-20003-1',
        jobId: '',
        jobName: 'Восстановление геометрии',
        description: 'Восстановление геометрии',
        quantity: 5,
        unitPrice: 4977.0,
        lineMarkup: 0,
        taxApplicable: true,
        position: 0,
      },
      {
        id: 'oj-xml-20003-2',
        jobId: '',
        jobName: 'Замена коронок',
        description: 'Замена коронок',
        quantity: 5,
        unitPrice: 5642.0,
        lineMarkup: 0,
        taxApplicable: true,
        position: 1,
      },
      {
        id: 'oj-xml-20003-3',
        jobId: '',
        jobName: 'Наплавка и расточка посадочных мест',
        description: 'Наплавка и расточка посадочных мест',
        quantity: 5,
        unitPrice: 4568.0,
        lineMarkup: 0,
        taxApplicable: true,
        position: 2,
      },
    ],
  },
  {
    id: 'ORD-XML-20021',
    clientId: 'client-xml-10004',
    status: 'completed',
    createdAt: new Date('2015-11-10T00:00:00'),
    updatedAt: new Date('2015-11-10T23:07:00'),
    taxRate: 8.5,
    globalMarkup: 20,
    currency: 'USD',
    orderType: 'Поставка',
    orderTitle: 'Поставка полумесяцев для шредера',
    jobs: [
      {
        id: 'oj-xml-20021-1',
        jobId: '',
        jobName: 'Поставка теплового насоса Energy Smart 20',
        description: 'Поставка теплового насоса Energy Smart 20',
        quantity: 2,
        unitPrice: 365200.0,
        lineMarkup: 10,
        taxApplicable: true,
        position: 0,
      },
      {
        id: 'oj-xml-20021-2',
        jobId: '',
        jobName: 'Поставка теплового насоса Energy HW20',
        description: 'Поставка теплового насоса Energy HW20',
        quantity: 2,
        unitPrice: 299200.0,
        lineMarkup: 10,
        taxApplicable: true,
        position: 1,
      },
    ],
  },
  {
    id: 'ORD-XML-20022',
    clientId: 'client-xml-10008',
    status: 'completed',
    createdAt: new Date('2015-11-10T00:00:00'),
    updatedAt: new Date('2015-11-10T23:07:00'),
    taxRate: 8.5,
    globalMarkup: 20,
    currency: 'USD',
    orderType: 'Поставка',
    orderTitle: 'Поставка полумесяцев для шредера',
    jobs: [
      {
        id: 'oj-xml-20022-1',
        jobId: '',
        jobName: 'Работы по замене полов на пресс-ножницах LIS 616',
        description: 'Работы по замене полов на пресс-ножницах LIS 616',
        quantity: 1,
        unitPrice: 66000.0,
        lineMarkup: 0,
        taxApplicable: true,
        position: 0,
      },
    ],
  },
];

export const mockJobPresets: JobPreset[] = [
  {
    id: 'preset-1',
    name: 'Standard Steel Welding Package',
    description: 'Common steel welding job with finishing',
    category: 'Welding',
    jobs: [
      { jobId: 'job-1', defaultQty: 4, position: 0 },
      { jobId: 'job-4', defaultQty: 2, position: 1 },
    ],
    lastUpdated: new Date('2024-10-01'),
  },
  {
    id: 'preset-2',
    name: 'Aluminum Fabrication Complete',
    description: 'Full aluminum welding and finishing service',
    category: 'Fabrication',
    jobs: [
      { jobId: 'job-2', defaultQty: 8, position: 0 },
      { jobId: 'job-9', defaultQty: 4, position: 1 },
      { jobId: 'job-8', defaultQty: 1, position: 2 },
    ],
    lastUpdated: new Date('2024-10-10'),
  },
  {
    id: 'preset-3',
    name: 'Custom Frame Build',
    description: 'Complete custom frame fabrication package',
    category: 'Fabrication',
    jobs: [
      { jobId: 'job-3', defaultQty: 6, position: 0 },
      { jobId: 'job-6', defaultQty: 1, position: 1 },
      { jobId: 'job-1', defaultQty: 10, position: 2 },
    ],
    lastUpdated: new Date('2024-09-25'),
  },
];

export const mockCompanySettings: CompanySettings = {
  name: 'Premium Welding & Fabrication',
  legalName: 'Premium Welding & Fabrication LLC',
  address: '2500 Industrial Park Dr, Detroit, MI 48210',
  phone: '(555) 987-6543',
  email: 'info@premiumwelding.com',
  taxId: '38-9876543',
  currency: 'USD',
  locale: 'en-US',
  defaultTaxRate: 8.5,
  defaultMarkup: 20,
  invoicePrefix: 'INV',
  poPrefix: 'PO',
};

export const mockDocumentTemplates: DocumentTemplate[] = [
  {
    id: 'template-1',
    name: 'Standard Invoice',
    type: 'invoice',
    htmlContent: '<div>Invoice template content</div>',
    isDefault: true,
    lastUpdated: new Date('2024-09-01'),
  },
  {
    id: 'template-2',
    name: 'Standard Purchase Order',
    type: 'purchase-order',
    htmlContent: '<div>PO template content</div>',
    isDefault: true,
    lastUpdated: new Date('2024-09-01'),
  },
];
