// Client detail page - view and manage a single client
import { useState, useMemo, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useApp } from '../lib/app-context';
import { useFormatting } from '../lib/use-formatting';
import { StatusPill } from '../components/status-pill';
import { 
  getClientOrders, 
  getClientLifetimeValue,
  calculateOrderTotal,
  generateId,
  formatPhoneNumber,
  normalizePhoneNumber,
  isValidEmail,
  extractIdNumbers
} from '../lib/utils';
import { ArrowLeft, Mail, Phone, MapPin, Edit, Plus, FileText, User, Save, Building2, Loader2 } from 'lucide-react';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Textarea } from '../components/ui/textarea';
import { PhoneInput } from '../components/ui/phone-input';
import { toast } from 'sonner';
import { logger } from '../lib/logger';
import type { Client } from '../lib/types';

interface ClientDetailProps {
  clientId: string;
  onNavigate: (page: string, id?: string) => void;
  previousPage?: { page: string; id?: string } | null;
}

export function ClientDetail({ clientId, onNavigate, previousPage }: ClientDetailProps) {
  const { t } = useTranslation();
  const { formatCurrency, formatDate } = useFormatting();
  const { clients, orders, addClient, updateClient } = useApp();
  const [isEditing, setIsEditing] = useState(clientId === 'new');
  const [activeTab, setActiveTab] = useState<'overview' | 'orders'>('overview');
  const [validationErrors, setValidationErrors] = useState<Record<string, string>>({});
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const [isSaving, setIsSaving] = useState(false);
  
  const isNewClient = clientId === 'new';
  const client = useMemo(() => 
    isNewClient ? null : clients.find(c => c.id === clientId),
    [clients, clientId, isNewClient]
  );
  
  // Reset editing state when clientId changes (e.g., after creating a new client)
  useEffect(() => {
    if (!isNewClient && client) {
      setIsEditing(false);
    } else if (isNewClient) {
      setIsEditing(true);
    }
  }, [clientId, isNewClient, client]);
  
  const [formData, setFormData] = useState<Partial<Client>>(
    client || {
      name: '',
      company: '',
      email: '',
      phone: '',
      address: '',
      inn: '',
      kpp: '',
      ogrn: '',
      bank: {
        name: '',
        accountNumber: '',
        correspondentAccount: '',
        bik: '',
      },
      notes: '',
    }
  );
  
  const clientOrders = useMemo(() => 
    client ? getClientOrders(orders, client.id) : [],
    [orders, client]
  );
  
  const lifetimeValue = useMemo(() =>
    client ? getClientLifetimeValue(orders, client.id) : 0,
    [orders, client]
  );
  
  const validateForm = (): boolean => {
    const errors: Record<string, string> = {};
    
    // At least one of name or company is required
    const hasName = formData.name && formData.name.trim() !== '';
    const hasCompany = formData.company && formData.company.trim() !== '';
    if (!hasName && !hasCompany) {
      errors.name = t('clientDetail.validation.nameOrCompanyRequired');
      errors.company = t('clientDetail.validation.nameOrCompanyRequired');
    }
    
    // Validate email format if provided
    if (formData.email && formData.email.trim() !== '') {
      if (!isValidEmail(formData.email)) {
        errors.email = t('clientDetail.validation.invalidEmail');
      }
    }
    
    // Validate phone format if provided
    const hasPhone = formData.phone && formData.phone.trim() !== '';
    const hasEmail = formData.email && formData.email.trim() !== '';
    
    // At least one of email or phone is required
    if (!hasEmail && !hasPhone) {
      errors.email = t('clientDetail.validation.emailOrPhoneRequired');
      errors.phone = t('clientDetail.validation.emailOrPhoneRequired');
    }
    
    setValidationErrors(errors);
    setTouched({
      name: true,
      company: true,
      email: true,
      phone: true,
    });
    
    return Object.keys(errors).length === 0;
  };

  const handleSave = async () => {
    if (!validateForm()) {
      return;
    }
    
    if (isNewClient) {
      setIsSaving(true);
      try {
        const newClient: Client = {
          id: 'new', // Will be generated by database sequence in addClient
          name: formData.name || '',
          company: formData.company || '',
          email: formData.email || '',
          phone: formData.phone || '',
          address: formData.address || '',
          inn: formData.inn,
          kpp: formData.kpp,
          ogrn: formData.ogrn,
          bank: formData.bank,
          notes: formData.notes,
          createdAt: new Date(),
          updatedAt: new Date(),
        };
        const generatedId = await addClient(newClient);
        
        // Wait a bit for the client to appear in the list
        // This ensures the client detail page can find the client
        await new Promise(resolve => setTimeout(resolve, 100));
        
        // Reset editing state before navigation
        setIsEditing(false);
        setValidationErrors({});
        setTouched({});
        
        toast.success(t('clientDetail.clientCreatedSuccess'));
        
        // Navigate to the new client page
        onNavigate('client-detail', generatedId);
      } catch (error) {
        logger.error('Error creating client', error);
        toast.error(t('clientDetail.clientCreationFailed'));
      } finally {
        setIsSaving(false);
      }
    } else if (client) {
      try {
        updateClient(client.id, formData);
        toast.success(t('clientDetail.clientUpdatedSuccess'));
        setIsEditing(false);
        setValidationErrors({});
        setTouched({});
      } catch (error) {
        logger.error('Error updating client', error);
        toast.error(t('clientDetail.clientUpdateFailed'));
      }
    }
  };
  
  const handleCancel = () => {
    if (isNewClient) {
      onNavigate('clients');
    } else {
      setFormData(client || {});
      setIsEditing(false);
      setValidationErrors({});
      setTouched({});
    }
  };

  const handleFieldChange = (field: keyof Client, value: string) => {
    setFormData({ ...formData, [field]: value });
    // Clear error when user starts typing
    if (validationErrors[field]) {
      // If clearing name/company error, check if requirement is now met
      if (field === 'name' || field === 'company') {
        const hasName = field === 'name' ? (value && value.trim() !== '') : (formData.name && formData.name.trim() !== '');
        const hasCompany = field === 'company' ? (value && value.trim() !== '') : (formData.company && formData.company.trim() !== '');
        if (hasName || hasCompany) {
          setValidationErrors({ ...validationErrors, name: '', company: '' });
        } else {
          setValidationErrors({ ...validationErrors, [field]: '' });
        }
      } else if (field === 'email' || field === 'phone') {
        // If clearing email/phone error, check if requirement is now met
        const hasPhone = field === 'phone' ? (value && value.trim() !== '') : (formData.phone && formData.phone.trim() !== '');
        const hasEmail = field === 'email' ? (value && value.trim() !== '') : (formData.email && formData.email.trim() !== '');
        if (hasPhone || hasEmail) {
          setValidationErrors({ ...validationErrors, email: '', phone: '' });
        } else {
          setValidationErrors({ ...validationErrors, [field]: '' });
        }
      } else {
        setValidationErrors({ ...validationErrors, [field]: '' });
      }
    }
  };

  const handleFieldBlur = (field: string) => {
    setTouched({ ...touched, [field]: true });
    
    // Validate on blur
    if (field === 'email') {
      if (formData.email && formData.email.trim() !== '') {
        if (!isValidEmail(formData.email)) {
          setValidationErrors({ ...validationErrors, email: t('clientDetail.validation.invalidEmail') });
        } else {
          // Clear email error, but check if phone/email requirement is met
          const hasPhone = formData.phone && formData.phone.trim() !== '';
          const hasEmail = formData.email && formData.email.trim() !== '';
          if (hasEmail || hasPhone) {
            setValidationErrors({ ...validationErrors, email: '', phone: '' });
          }
        }
      } else {
        // Email is empty, check if phone is provided
        const hasPhone = formData.phone && formData.phone.trim() !== '';
        if (!hasPhone) {
          setValidationErrors({ ...validationErrors, email: t('clientDetail.validation.emailOrPhoneRequired'), phone: t('clientDetail.validation.emailOrPhoneRequired') });
        } else {
          setValidationErrors({ ...validationErrors, email: '', phone: '' });
        }
      }
    } else if (field === 'phone') {
      // Phone field blurred, check if email/phone requirement is met
      const hasPhone = formData.phone && formData.phone.trim() !== '';
      const hasEmail = formData.email && formData.email.trim() !== '';
      if (!hasEmail && !hasPhone) {
        setValidationErrors({ ...validationErrors, email: t('clientDetail.validation.emailOrPhoneRequired'), phone: t('clientDetail.validation.emailOrPhoneRequired') });
      } else {
        setValidationErrors({ ...validationErrors, email: '', phone: '' });
      }
    } else if (field === 'name' || field === 'company') {
      // Name or company field blurred, check if name/company requirement is met
      const hasName = formData.name && formData.name.trim() !== '';
      const hasCompany = formData.company && formData.company.trim() !== '';
      if (!hasName && !hasCompany) {
        setValidationErrors({ ...validationErrors, name: t('clientDetail.validation.nameOrCompanyRequired'), company: t('clientDetail.validation.nameOrCompanyRequired') });
      } else {
        setValidationErrors({ ...validationErrors, name: '', company: '' });
      }
    }
  };
  
  if (!isNewClient && !client) {
    return (
      <div className="text-center py-12">
        <p className="text-[#7C8085] mb-4">{t('clientDetail.clientNotFound')}</p>
        <button
          onClick={() => {
            if (previousPage) {
              onNavigate(previousPage.page, previousPage.id);
            } else {
              onNavigate('clients');
            }
          }}
          className="px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors cursor-pointer"
        >
          {t('clientDetail.backToClients')}
        </button>
      </div>
    );
  }
  
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <button
            onClick={() => {
              if (previousPage) {
                onNavigate(previousPage.page, previousPage.id);
              } else {
                onNavigate('clients');
              }
            }}
            className="p-2 hover:bg-[#E4E7E7] rounded-lg transition-colors cursor-pointer"
            aria-label={t('clientDetail.backToClients')}
          >
            <ArrowLeft size={20} aria-hidden="true" />
          </button>
          <div>
            <h1 className="text-[#1E2025] mb-1">
              {isNewClient ? t('clientDetail.newClient') : (isEditing ? t('clientDetail.editClient') : (client?.company && client.company.trim() !== '' ? client.company : (client?.name && client.name !== 'Unknown' && client.name.trim() !== '' ? client.name : t('clientDetail.newClient'))))}
            </h1>
            {!isNewClient && !isEditing && client && (
              <p className="text-[#555A60]">{t('clientDetail.clientNumber', { number: extractIdNumbers(client.id) })}</p>
            )}
          </div>
        </div>
        <div className="flex flex-wrap gap-3 justify-end">
          {isEditing ? (
            <>
              <button
                onClick={handleCancel}
                className="px-4 py-2 bg-[#E4E7E7] text-[#1E2025] rounded-lg hover:bg-[#D2D6D6] transition-colors"
              >
                {t('clientDetail.cancel')}
              </button>
              <button
                onClick={handleSave}
                disabled={isSaving}
                className="flex items-center gap-2 px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isSaving ? (
                  <>
                    <Loader2 size={20} className="animate-spin" aria-hidden="true" />
                    {t('common.saving')}
                  </>
                ) : (
                  <>
                    <Save size={20} aria-hidden="true" />
                    {isNewClient ? t('clientDetail.createClient') : t('common.saveChanges')}
                  </>
                )}
              </button>
            </>
          ) : (
            <>
              <button
                onClick={() => setIsEditing(true)}
                className="flex items-center gap-2 px-4 py-2 bg-[#E4E7E7] text-[#1E2025] rounded-lg hover:bg-[#D2D6D6] transition-colors"
              >
                <Edit size={20} aria-hidden="true" />
                {t('clientDetail.edit')}
              </button>
              <button
                onClick={() => onNavigate('order-detail', `new?client=${client?.id}`)}
                className="flex items-center gap-2 px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors"
              >
                <Plus size={20} aria-hidden="true" />
                {t('clientDetail.newOrder')}
              </button>
            </>
          )}
        </div>
      </div>
      
      {isEditing ? (
        /* Edit Form */
        <div className="bg-white rounded-xl border border-[#E4E7E7] p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label htmlFor="name">{t('clientDetail.name')} *</Label>
              <Input
                id="name"
                value={formData.name || ''}
                onChange={(e) => handleFieldChange('name', e.target.value)}
                onBlur={() => handleFieldBlur('name')}
                aria-invalid={touched.name && !!validationErrors.name}
                className={touched.name && validationErrors.name ? 'border-red-500 focus-visible:border-red-500 focus-visible:ring-red-500/50' : ''}
              />
              {touched.name && validationErrors.name && (
                <p className="text-sm text-red-600">{validationErrors.name}</p>
              )}
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="company">{t('clients.company')} *</Label>
              <Input
                id="company"
                value={formData.company || ''}
                onChange={(e) => handleFieldChange('company', e.target.value)}
                onBlur={() => handleFieldBlur('company')}
                aria-invalid={touched.company && !!validationErrors.company}
                className={touched.company && validationErrors.company ? 'border-red-500 focus-visible:border-red-500 focus-visible:ring-red-500/50' : ''}
              />
              {touched.company && validationErrors.company && (
                <p className="text-sm text-red-600">{validationErrors.company}</p>
              )}
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="email">{t('clientDetail.email')} *</Label>
              <Input
                id="email"
                type="email"
                value={formData.email || ''}
                onChange={(e) => handleFieldChange('email', e.target.value)}
                onBlur={() => handleFieldBlur('email')}
                aria-invalid={touched.email && !!validationErrors.email}
                className={touched.email && validationErrors.email ? 'border-red-500 focus-visible:border-red-500 focus-visible:ring-red-500/50' : ''}
              />
              {touched.email && validationErrors.email && (
                <p className="text-sm text-red-600">{validationErrors.email}</p>
              )}
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="phone">{t('clientDetail.phone')} *</Label>
              <PhoneInput
                id="phone"
                value={formData.phone || ''}
                onChange={(value) => handleFieldChange('phone', value)}
                onBlur={() => handleFieldBlur('phone')}
                aria-invalid={touched.phone && !!validationErrors.phone}
                className={touched.phone && validationErrors.phone ? 'border-red-500 focus-visible:border-red-500 focus-visible:ring-red-500/50' : ''}
              />
              {touched.phone && validationErrors.phone && (
                <p className="text-sm text-red-600">{validationErrors.phone}</p>
              )}
            </div>
            
            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="address">{t('clientDetail.address')}</Label>
              <Input
                id="address"
                value={formData.address || ''}
                onChange={(e) => setFormData({ ...formData, address: e.target.value })}
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="inn">{t('clientDetail.innTaxId')}</Label>
              <Input
                id="inn"
                value={formData.inn || ''}
                onChange={(e) => setFormData({ ...formData, inn: e.target.value })}
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="kpp">{t('clientDetail.kpp')}</Label>
              <Input
                id="kpp"
                value={formData.kpp || ''}
                onChange={(e) => setFormData({ ...formData, kpp: e.target.value })}
              />
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="ogrn">{t('clientDetail.ogrn')}</Label>
              <Input
                id="ogrn"
                value={formData.ogrn || ''}
                onChange={(e) => setFormData({ ...formData, ogrn: e.target.value })}
              />
            </div>
            
            <div className="space-y-2 md:col-span-2">
              <Label className="text-[#555A60] font-medium">{t('clientDetail.bankingInformation')}</Label>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2">
                <div className="space-y-2">
                  <Label htmlFor="bankName">{t('clientDetail.bankName')}</Label>
                  <Input
                    id="bankName"
                    value={formData.bank?.name || ''}
                    onChange={(e) => setFormData({ 
                      ...formData, 
                      bank: { ...formData.bank, name: e.target.value }
                    })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="bankAccount">{t('clientDetail.accountNumber')}</Label>
                  <Input
                    id="bankAccount"
                    value={formData.bank?.accountNumber || ''}
                    onChange={(e) => setFormData({ 
                      ...formData, 
                      bank: { ...formData.bank, accountNumber: e.target.value }
                    })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="bankCorrespondent">{t('clientDetail.correspondentAccount')}</Label>
                  <Input
                    id="bankCorrespondent"
                    value={formData.bank?.correspondentAccount || ''}
                    onChange={(e) => setFormData({ 
                      ...formData, 
                      bank: { ...formData.bank, correspondentAccount: e.target.value }
                    })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="bankBik">{t('clientDetail.bik')}</Label>
                  <Input
                    id="bankBik"
                    value={formData.bank?.bik || ''}
                    onChange={(e) => setFormData({ 
                      ...formData, 
                      bank: { ...formData.bank, bik: e.target.value }
                    })}
                  />
                </div>
              </div>
            </div>
            
            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="notes">{t('clientDetail.notes')}</Label>
              <Textarea
                id="notes"
                value={formData.notes || ''}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                rows={4}
              />
            </div>
          </div>
        </div>
      ) : (
        /* View Mode */
        <>
          {/* Client Info Card */}
          <div className="bg-white rounded-xl border border-[#E4E7E7] p-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <h3 className="text-[#555A60] mb-4 font-semibold text-base">{t('clientDetail.contactInformation')}</h3>
                <div className="space-y-3">
                  <div className="flex items-start gap-3">
                    <User size={20} className="text-[#7C8085] mt-0.5 flex-shrink-0" aria-hidden="true" />
                    <div>
                      <p className="text-[#7C8085]">{t('clientDetail.name')}</p>
                      <p className="text-[#1E2025]">
                        {client?.name && client.name !== 'Unknown' && client.name.trim() !== '' 
                          ? client.name 
                          : t('clientDetail.notProvided')}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <Building2 size={20} className="text-[#7C8085] mt-0.5 flex-shrink-0" aria-hidden="true" />
                    <div>
                      <p className="text-[#7C8085]">{t('clients.company')}</p>
                      <p className="text-[#1E2025]">
                        {client?.company && client.company.trim() !== '' 
                          ? client.company 
                          : t('clientDetail.notProvided')}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <Mail size={20} className="text-[#7C8085] mt-0.5 flex-shrink-0" aria-hidden="true" />
                    <div>
                      <p className="text-[#7C8085]">{t('clientDetail.email')}</p>
                      {client?.email && client.email.trim() !== '' ? (
                        <a 
                          href={`mailto:${client.email}`}
                          className="text-[#1F744F] hover:underline"
                        >
                          {client.email}
                        </a>
                      ) : (
                        <p className="text-[#1E2025]">{t('clientDetail.notProvided')}</p>
                      )}
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <Phone size={20} className="text-[#7C8085] mt-0.5 flex-shrink-0" aria-hidden="true" />
                    <div>
                      <p className="text-[#7C8085]">{t('clientDetail.phone')}</p>
                      {client?.phone && client.phone.trim() !== '' ? (
                        <a 
                          href={`tel:${'7' + normalizePhoneNumber(client.phone).substring(1)}`}
                          className="text-[#1E2025]"
                        >
                          {formatPhoneNumber(client.phone)}
                        </a>
                      ) : (
                        <p className="text-[#1E2025]">{t('clientDetail.notProvided')}</p>
                      )}
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <MapPin size={20} className="text-[#7C8085] mt-0.5 flex-shrink-0" aria-hidden="true" />
                    <div>
                      <p className="text-[#7C8085]">{t('clientDetail.address')}</p>
                      <p className="text-[#1E2025]">{client?.address && client.address.trim() !== '' ? client.address : t('clientDetail.notProvided')}</p>
                    </div>
                  </div>
                </div>
              </div>
              
              <div>
                <h3 className="text-[#555A60] mb-4 font-semibold text-base">{t('clientDetail.taxInformation')}</h3>
                <div className="space-y-3">
                  <div>
                    <p className="text-[#7C8085]">{t('clientDetail.inn')}</p>
                    <p className="text-[#1E2025]">{client?.inn || t('clientDetail.notProvided')}</p>
                  </div>
                  <div>
                    <p className="text-[#7C8085]">{t('clientDetail.kpp')}</p>
                    <p className="text-[#1E2025]">{client?.kpp || t('clientDetail.notProvided')}</p>
                  </div>
                  <div>
                    <p className="text-[#7C8085]">{t('clientDetail.ogrn')}</p>
                    <p className="text-[#1E2025]">{client?.ogrn || t('clientDetail.notProvided')}</p>
                  </div>
                </div>
              </div>
              
              <div>
                <h3 className="text-[#555A60] mb-4 font-semibold text-base">{t('clientDetail.statistics')}</h3>
                <div className="space-y-3">
                  <div>
                    <p className="text-[#7C8085]">{t('clientDetail.totalOrders')}</p>
                    <p className="text-[#1E2025]">{clientOrders.length}</p>
                  </div>
                  <div>
                    <p className="text-[#7C8085]">{t('clientDetail.lifetimeValue')}</p>
                    <p className="text-[#1E2025]">{formatCurrency(lifetimeValue)}</p>
                  </div>
                </div>
              </div>
            </div>
            
            {client?.bank && (client.bank.name || client.bank.accountNumber || client.bank.correspondentAccount || client.bank.bik) && (
              <div className="mt-6 pt-6 border-t border-[#E4E7E7]">
                <h3 className="text-[#555A60] mb-4">{t('clientDetail.bankingInformation')}</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {client.bank.name && (
                    <div>
                      <p className="text-[#7C8085]">{t('clientDetail.bankName')}</p>
                      <p className="text-[#1E2025]">{client.bank.name}</p>
                    </div>
                  )}
                  {client.bank.accountNumber && (
                    <div>
                      <p className="text-[#7C8085]">{t('clientDetail.accountNumber')}</p>
                      <p className="text-[#1E2025]">{client.bank.accountNumber}</p>
                    </div>
                  )}
                  {client.bank.correspondentAccount && (
                    <div>
                      <p className="text-[#7C8085]">{t('clientDetail.correspondentAccount')}</p>
                      <p className="text-[#1E2025]">{client.bank.correspondentAccount}</p>
                    </div>
                  )}
                  {client.bank.bik && (
                    <div>
                      <p className="text-[#7C8085]">{t('clientDetail.bik')}</p>
                      <p className="text-[#1E2025]">{client.bank.bik}</p>
                    </div>
                  )}
                </div>
              </div>
            )}
            
            {client?.notes && (
              <div className="mt-6 pt-6 border-t border-[#E4E7E7]">
                <h3 className="text-[#555A60] mb-2 font-semibold text-base">{t('clientDetail.notes')}</h3>
                <p className="text-[#1E2025]">{client.notes}</p>
              </div>
            )}
          </div>
          
          {/* Tabs */}
          <div className="border-b border-[#E4E7E7]">
            <nav className="flex gap-6" role="tablist">
              <button
                role="tab"
                aria-selected={activeTab === 'overview'}
                onClick={() => setActiveTab('overview')}
                className={`px-4 py-3 border-b-2 transition-colors cursor-pointer ${
                  activeTab === 'overview'
                    ? 'border-[#1F744F] text-[#1F744F]'
                    : 'border-transparent text-[#7C8085] hover:text-[#1E2025]'
                }`}
              >
                {t('clientDetail.overview')}
              </button>
              <button
                role="tab"
                aria-selected={activeTab === 'orders'}
                onClick={() => setActiveTab('orders')}
                className={`px-4 py-3 border-b-2 transition-colors cursor-pointer ${
                  activeTab === 'orders'
                    ? 'border-[#1F744F] text-[#1F744F]'
                    : 'border-transparent text-[#7C8085] hover:text-[#1E2025]'
                }`}
              >
                {t('clientDetail.orders')} ({clientOrders.length})
              </button>
            </nav>
          </div>
          
          {/* Tab Content */}
          {activeTab === 'overview' && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="bg-white rounded-xl border border-[#E4E7E7] p-6">
                <h3 className="text-[#1E2025] mb-4 font-semibold text-base">{t('clientDetail.recentOrders')}</h3>
                {clientOrders.length === 0 ? (
                  <p className="text-[#7C8085]">{t('clientDetail.noOrders')}</p>
                ) : (
                  <div className="space-y-3">
                    {clientOrders.slice(0, 5).map(order => (
                      <button
                        key={order.id}
                        onClick={() => onNavigate('order-detail', order.id)}
                        className="w-full flex items-center justify-between p-3 hover:bg-[#F7F8F8] rounded-lg transition-colors text-left cursor-pointer"
                      >
                        <div>
                          <p className="text-[#1E2025]">{t('orders.orderNumberPrefix')}{extractIdNumbers(order.id)}</p>
                          <p className="text-[#7C8085]">{formatDate(order.createdAt)}</p>
                        </div>
                        <div className="flex items-center gap-3">
                          <StatusPill status={order.status} />
                          <p className="text-[#1E2025]">{formatCurrency(calculateOrderTotal(order))}</p>
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}
          
          {activeTab === 'orders' && (
            <div className="bg-white rounded-xl border border-[#E4E7E7] overflow-hidden">
              {clientOrders.length === 0 ? (
                <div className="px-6 py-12 text-center">
                  <FileText size={48} className="mx-auto text-[#B5BDB9] mb-4" aria-hidden="true" />
                  <p className="text-[#7C8085] mb-4">{t('clientDetail.noOrders')}</p>
                  <button
                    onClick={() => onNavigate('orders', `new?client=${client?.id}`)}
                    className="px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors cursor-pointer"
                  >
                    {t('orders.createFirstOrder')}
                  </button>
                </div>
              ) : (
                <>
                  <table className="w-full">
                    <thead>
                      <tr className="border-b border-[#E4E7E7]">
                        <th className="px-6 py-3 text-left text-[#555A60]">{t('orders.orderTitle')}</th>
                        <th className="px-6 py-3 text-left text-[#555A60]">{t('orders.date')}</th>
                        <th className="px-6 py-3 text-left text-[#555A60]">{t('orders.status')}</th>
                        <th className="px-6 py-3 text-left text-[#555A60]">{t('orders.total')}</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-[#E4E7E7]">
                      {clientOrders.slice(0, 10).map(order => (
                        <tr
                          key={order.id}
                          onClick={() => onNavigate('order-detail', order.id)}
                          className="hover:bg-[#F7F8F8] cursor-pointer transition-colors"
                        >
                          <td className="px-6 py-4">
                            <p className="text-[#1E2025]">{order.orderTitle || `${t('orders.orderNumberPrefix')}${extractIdNumbers(order.id)}`}</p>
                          </td>
                          <td className="px-6 py-4">
                            <p className="text-[#555A60]">{formatDate(order.createdAt)}</p>
                          </td>
                          <td className="px-6 py-4">
                            <StatusPill status={order.status} />
                          </td>
                          <td className="px-6 py-4">
                            <p className="text-[#1E2025]">{formatCurrency(calculateOrderTotal(order))}</p>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  {clientOrders.length > 10 && (
                    <div className="px-6 py-4 border-t border-[#E4E7E7]">
                      <button
                        onClick={() => onNavigate('orders', `?client=${client?.id}`)}
                        className="text-[#1F744F] hover:text-[#165B3C] transition-colors cursor-pointer"
                      >
                        {t('clientDetail.viewMoreOrders')} ({clientOrders.length - 10} {t('common.more')})
                      </button>
                    </div>
                  )}
                </>
              )}
            </div>
          )}
        </>
      )}
    </div>
  );
}
