// Job catalog page - manage job templates
import { useState, useMemo, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useApp } from '../lib/app-context';
import { useFormatting } from '../lib/use-formatting';
import { generateId } from '../lib/utils';
import { logger } from '../lib/logger';
import { Search, Plus, Edit, Trash2, Loader2 } from 'lucide-react';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Textarea } from '../components/ui/textarea';
import { PaginationWithLinks } from '../components/ui/pagination-with-links';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '../components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '../components/ui/alert-dialog';
import { toast } from 'sonner';
import type { JobTemplate } from '../lib/types';

interface JobCatalogProps {
  onNavigate: (page: string, id?: string) => void;
}

export function JobCatalog({ onNavigate }: JobCatalogProps) {
  const { t, i18n } = useTranslation();
  const { formatCurrency, formatDate } = useFormatting();
  const { jobTemplates, jobPresets, addJobTemplate, updateJobTemplate, deleteJobTemplate, updateJobPreset } = useApp();
  const [searchQuery, setSearchQuery] = useState('');
  const [categoryFilter, setCategoryFilter] = useState<string>('all');
  const [editingJob, setEditingJob] = useState<JobTemplate | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [jobToDelete, setJobToDelete] = useState<JobTemplate | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  
  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 25;
  const [formData, setFormData] = useState<Partial<JobTemplate>>({
    name: '',
    description: '',
    category: '',
    unitPrice: 0,
    unitOfMeasure: i18n.language === 'ru' ? 'шт' : 'unit',
    defaultTax: true,
  });
  
  const categories = useMemo(() => {
    const cats = new Set(jobTemplates.map(j => j.category));
    return ['all', ...Array.from(cats)];
  }, [jobTemplates]);
  
  const filteredJobs = useMemo(() => {
    const query = searchQuery.toLowerCase().trim();
    const queryWords = query.split(/\s+/).filter(word => word.length > 0);
    
    return jobTemplates.filter(job => {
      const matchesSearch = queryWords.length === 0 || (() => {
        const searchableText = `${job.name} ${job.description} ${job.category}`.toLowerCase();
        // Check if all query words appear in the searchable text
        return queryWords.every(word => searchableText.includes(word));
      })();
      
      const matchesCategory = categoryFilter === 'all' || job.category === categoryFilter;
      
      return matchesSearch && matchesCategory;
    });
  }, [jobTemplates, searchQuery, categoryFilter]);
  
  // Pagination calculations
  const totalPages = Math.ceil(filteredJobs.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const paginatedJobs = filteredJobs.slice(startIndex, endIndex);
  
  // Reset to page 1 when filters change
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, categoryFilter]);
  
  const handleOpenCreate = () => {
    setFormData({
      name: '',
      description: '',
      category: '',
      unitPrice: 0,
      unitOfMeasure: i18n.language === 'ru' ? 'шт' : 'unit',
      defaultTax: true,
    });
    setEditingJob(null);
    setIsCreating(true);
  };
  
  const handleOpenEdit = (job: JobTemplate) => {
    setFormData(job);
    setEditingJob(job);
    setIsCreating(true);
  };
  
  const handleClose = () => {
    setIsCreating(false);
    setEditingJob(null);
    setFormData({
      name: '',
      description: '',
      category: '',
      unitPrice: 0,
      unitOfMeasure: i18n.language === 'ru' ? 'шт' : 'unit',
      defaultTax: true,
    });
    setIsSaving(false);
  };
  
  const handleSave = async () => {
    if (!formData.name || !formData.category || formData.unitPrice === undefined) {
      toast.error(t('jobCatalog.fillRequiredFields'));
      return;
    }
    
    if (isSaving) return; // Prevent double-clicking
    
    setIsSaving(true);
    
    try {
      let jobId: string;
      
      if (editingJob) {
        jobId = editingJob.id;
        await updateJobTemplate(editingJob.id, formData);
        toast.success(t('jobCatalog.jobTemplateUpdated'));
      } else {
        const newJob: JobTemplate = {
          id: 'new', // Will be generated by database sequence in addJobTemplate
          name: formData.name,
          description: formData.description || '',
          category: formData.category,
          unitPrice: formData.unitPrice,
          unitOfMeasure: formData.unitOfMeasure || (i18n.language === 'ru' ? 'шт' : 'unit'),
          defaultTax: formData.defaultTax ?? true,
          lastUpdated: new Date(),
        };
        jobId = newJob.id;
        await addJobTemplate(newJob);
        toast.success(t('jobCatalog.jobTemplateCreated'));
      }
      
      handleClose();
    } catch (error: any) {
      logger.error('Error saving job', error);
      toast.error(error?.message || t('jobCatalog.saveFailed') || 'Failed to save job');
    } finally {
      setIsSaving(false);
    }
  };
  
  const handleDelete = (job: JobTemplate) => {
    setJobToDelete(job);
    setShowDeleteDialog(true);
  };
  
  const handleConfirmDelete = async () => {
    if (!jobToDelete) return;
    
    try {
      // Remove job from all presets
      const presetsWithJob = jobPresets.filter(preset => 
        preset.jobs.some(presetJob => presetJob.jobId === jobToDelete.id)
      );
      
      for (const preset of presetsWithJob) {
        const updatedJobs = preset.jobs
          .filter(presetJob => presetJob.jobId !== jobToDelete.id)
          .map((presetJob, index) => ({ ...presetJob, position: index }));
        await updateJobPreset(preset.id, { jobs: updatedJobs });
      }
      
      await deleteJobTemplate(jobToDelete.id);
      toast.success(t('jobCatalog.jobTemplateDeleted'));
      setJobToDelete(null);
    } catch (error: any) {
      logger.error('Error deleting job', error);
      toast.error(error?.message || t('jobCatalog.deleteFailed') || 'Failed to delete job');
    } finally {
      setShowDeleteDialog(false);
    }
  };
  
  const handleCancelDelete = () => {
    setShowDeleteDialog(false);
    setJobToDelete(null);
  };
  
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-[#1E2025] mb-2">{t('jobCatalog.title')}</h1>
          <p className="text-[#555A60]">{t('jobCatalog.subtitle')}</p>
        </div>
        <button
          onClick={handleOpenCreate}
          className="flex items-center gap-2 px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors cursor-pointer whitespace-nowrap"
        >
          <Plus size={20} aria-hidden="true" />
          {t('jobCatalog.newJob')}
        </button>
      </div>
      
      {/* Filters */}
      <div className="flex items-center gap-4 flex-wrap">
        <div className="flex-1 min-w-[300px] max-w-md relative">
          <Search 
            className="absolute left-3 top-1/2 -translate-y-1/2 text-[#7C8085]" 
            size={20}
            aria-hidden="true"
          />
          <Input
            type="search"
            placeholder={t('jobCatalog.searchPlaceholder')}
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-10"
            aria-label={t('jobCatalog.searchLabel')}
          />
        </div>
        
        <div className="flex gap-2 flex-wrap">
          {categories.map(cat => (
            <button
              key={cat}
                    onClick={() => setCategoryFilter(cat)}
                    className={`px-3 py-2 rounded-lg transition-colors capitalize cursor-pointer ${
                      categoryFilter === cat
                        ? 'bg-[#1F744F] text-white'
                        : 'bg-white text-[#555A60] border border-[#E4E7E7] hover:bg-[#F7F8F8]'
                    }`}
                  >
              {cat === 'all' ? t('jobCatalog.all') : cat}
            </button>
          ))}
        </div>
      </div>
      
      {/* Jobs Grid */}
      {filteredJobs.length === 0 ? (
        <div className="bg-white rounded-xl border border-[#E4E7E7] px-6 py-12 text-center">
          {searchQuery || categoryFilter !== 'all' ? (
            <>
              <p className="text-[#7C8085] mb-2">{t('jobCatalog.noJobs')}</p>
              <p className="text-[#7C8085]">{t('jobCatalog.noJobsDescription')}</p>
            </>
          ) : (
            <>
              <p className="text-[#7C8085] mb-4">{t('jobCatalog.noJobTemplates')}</p>
              <button
                onClick={handleOpenCreate}
                className="px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors cursor-pointer"
              >
                {t('jobCatalog.createFirstJobTemplate')}
              </button>
            </>
          )}
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {paginatedJobs.map(job => (
            <div
              key={job.id}
              onClick={() => handleOpenEdit(job)}
              className="bg-white rounded-xl border border-[#E4E7E7] p-6 hover:border-[#1F744F] transition-colors cursor-pointer"
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex-1">
                  <h3 className="text-[#1E2025] mb-1">{job.name}</h3>
                  <span className="inline-block px-2 py-1 bg-[#F2F4F4] text-[#7C8085] rounded text-sm">
                    {job.category}
                  </span>
                </div>
                <div className="flex gap-1">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleOpenEdit(job);
                          }}
                          className="p-2 text-[#555A60] hover:bg-[#F7F8F8] rounded-lg transition-colors cursor-pointer"
                          aria-label={`Edit ${job.name}`}
                        >
                          <Edit size={16} />
                        </button>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleDelete(job);
                          }}
                          className="p-2 text-[#E5484D] hover:bg-[#FEE] rounded-lg transition-colors cursor-pointer"
                          aria-label={`Delete ${job.name}`}
                        >
                    <Trash2 size={16} />
                  </button>
                </div>
              </div>
              
              <div className="flex items-center justify-between pt-4 border-t border-[#E4E7E7]">
                <div>
                  <p className="text-[#7C8085]">{t('jobCatalog.defaultPrice')}</p>
                  <p className="text-[#1F744F]">
                    {formatCurrency(job.unitPrice)} / {job.unitOfMeasure}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-[#7C8085]">{t('jobCatalog.updated')}</p>
                  <p className="text-[#555A60]">{formatDate(job.lastUpdated)}</p>
                </div>
              </div>
            </div>
          ))}
          </div>
          
          {filteredJobs.length > 0 && (
            <div className="flex items-center justify-between">
              <p className="text-[#555A60] text-sm">
                {t('jobCatalog.showing')} {startIndex + 1} {t('jobCatalog.to')} {Math.min(endIndex, filteredJobs.length)} {t('jobCatalog.of')} {filteredJobs.length} {t('jobCatalog.jobs')}
                {filteredJobs.length !== jobTemplates.length && ` (${t('jobCatalog.filteredFrom')} ${jobTemplates.length} ${t('jobCatalog.total')})`}
              </p>
              <PaginationWithLinks
                page={currentPage}
                pageSize={itemsPerPage}
                totalCount={filteredJobs.length}
                onPageChange={setCurrentPage}
              />
            </div>
          )}
        </>
      )}
      
      {/* Edit/Create Dialog */}
      <Dialog open={isCreating} onOpenChange={handleClose}>
        <DialogContent className="sm:max-w-[600px]">
          <DialogHeader>
            <DialogTitle>
              {editingJob ? t('jobCatalog.editJobTemplate') : t('jobCatalog.createJobTemplate')}
            </DialogTitle>
          </DialogHeader>
          
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="jobName">{t('jobCatalog.jobName')} *</Label>
                <Input
                  id="jobName"
                  value={formData.name || ''}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder={t('jobCatalog.jobNamePlaceholder')}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="category">{t('jobCatalog.category')} *</Label>
                <Input
                  id="category"
                  value={formData.category || ''}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  placeholder={t('jobCatalog.categoryPlaceholder')}
                />
              </div>
            </div>
            
            <div className="space-y-2">
              <Label htmlFor="description">{t('jobCatalog.description')}</Label>
              <Textarea
                id="description"
                value={formData.description || ''}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                placeholder={t('jobCatalog.descriptionPlaceholder')}
                rows={3}
              />
            </div>
            
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="unitPrice">{t('jobCatalog.unitPrice')} *</Label>
                <Input
                  id="unitPrice"
                  type="number"
                  min="0"
                  step="0.01"
                  value={formData.unitPrice || ''}
                  onChange={(e) => setFormData({ 
                    ...formData, 
                    unitPrice: parseFloat(e.target.value) || 0 
                  })}
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="unitOfMeasure">{t('jobCatalog.unitOfMeasure')}</Label>
                <Input
                  id="unitOfMeasure"
                  value={formData.unitOfMeasure || ''}
                  onChange={(e) => setFormData({ ...formData, unitOfMeasure: e.target.value })}
                  placeholder={t('jobCatalog.unitOfMeasurePlaceholder')}
                />
              </div>
            </div>
          </div>
          
          <DialogFooter>
              <button
                onClick={handleClose}
                className="px-4 py-2 bg-[#E4E7E7] text-[#1E2025] rounded-lg hover:bg-[#D2D6D6] transition-colors cursor-pointer"
              >
                {t('jobCatalog.cancel')}
              </button>
              <button
                onClick={handleSave}
                disabled={isSaving}
                className="flex items-center gap-2 px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
              >
                {isSaving ? (
                  <>
                    <Loader2 size={16} className="animate-spin" aria-hidden="true" />
                    {t('common.saving') || 'Saving...'}
                  </>
                ) : (
                  editingJob ? t('common.saveChanges') : t('jobCatalog.createJob')
                )}
            </button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      
      {/* Delete Confirmation Dialog */}
      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent className="bg-white border border-[#E4E7E7]">
          <AlertDialogHeader>
            <AlertDialogTitle className="text-[#1E2025]">
              {t('jobCatalog.deleteConfirmTitle') || t('jobCatalog.deleteConfirm')}
            </AlertDialogTitle>
            <AlertDialogDescription className="text-[#555A60]">
              {jobToDelete 
                ? (t('jobCatalog.deleteConfirmDescription', { jobName: jobToDelete.name }) || t('jobCatalog.deleteConfirm'))
                : t('jobCatalog.deleteConfirm')
              }
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter className="flex-col-reverse sm:flex-row gap-2">
            <AlertDialogCancel
              onClick={handleCancelDelete}
              className="bg-[#E4E7E7] text-[#1E2025] hover:bg-[#D2D6D6] m-0"
            >
              {t('common.cancel') || 'Cancel'}
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleConfirmDelete}
              className="bg-[#1F744F] text-white hover:bg-[#165B3C] m-0"
            >
              {t('jobCatalog.delete') || 'Delete'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
