// Order detail page - create and manage orders with job line items
import { useState, useMemo, useEffect, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { useApp } from '../lib/app-context';
import { useFormatting } from '../lib/use-formatting';
import { 
  calculateLineTotal,
  getOrderTotals,
  generateOrderId,
  generateId,
  generateDocumentNumber
} from '../lib/utils';
import { generateInvoice, generatePurchaseOrder } from '../lib/document-generator';
import { 
  ArrowLeft, 
  Plus, 
  Trash2, 
  Save,
  FileText,
  Layers,
  Search,
  Loader2,
  Copy,
  Edit2,
  Check,
  X
} from 'lucide-react';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Textarea } from '../components/ui/textarea';
import { Button } from '../components/ui/button';
import { 
  Select, 
  SelectContent, 
  SelectItem, 
  SelectTrigger, 
  SelectValue 
} from '../components/ui/select';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '../components/ui/popover';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '../components/ui/alert-dialog';
import type { Order, OrderJob, OrderStatus } from '../lib/types';
import { toast } from 'sonner';

// Order type options
const ORDER_TYPES = [
  { value: 'Поставка', labelEn: 'Supply/Delivery', labelRu: 'Поставка' },
  { value: 'Ремонтные работы', labelEn: 'Repair work', labelRu: 'Ремонтные работы' },
  { value: 'Оказание иных услуг', labelEn: 'Provision of other services', labelRu: 'Оказание иных услуг' },
];

interface OrderDetailProps {
  orderId: string;
  onNavigate: (page: string, id?: string) => void;
}

export function OrderDetail({ orderId, onNavigate }: OrderDetailProps) {
  const { t, i18n } = useTranslation();
  const { orders, clients, jobTemplates, jobPresets, companySettings, addOrder, updateOrder } = useApp();
  const { formatCurrency } = useFormatting();
  
  // Get order type label based on current language
  const getOrderTypeLabel = (value: string) => {
    const orderType = ORDER_TYPES.find(ot => ot.value === value);
    if (!orderType) return value;
    return i18n.language === 'ru' ? orderType.labelRu : orderType.labelEn;
  };
  const [generatingInvoice, setGeneratingInvoice] = useState(false);
  const [generatingPO, setGeneratingPO] = useState(false);
  
  // Parse orderId to extract client ID from query string (e.g., "new?client=client-10328")
  const parsedOrderId = orderId?.includes('?') ? orderId.split('?')[0] : orderId;
  const clientIdFromQuery = orderId?.includes('?client=') 
    ? orderId.split('?client=')[1]?.split('&')[0] 
    : null;
  
  const isNewOrder = parsedOrderId === 'new';
  const existingOrder = useMemo(() => 
    isNewOrder ? null : orders.find(o => o.id === parsedOrderId),
    [orders, parsedOrderId, isNewOrder]
  );
  
  const [formData, setFormData] = useState<Partial<Order>>(
    existingOrder || {
      id: 'new', // Will be generated by database sequence in addOrder
      clientId: clientIdFromQuery || '',
      status: 'proposal',
      taxRate: 8.5,
      globalMarkup: 20,
      currency: 'USD',
      orderType: 'Ремонтные работы',
      orderTitle: '',
      jobs: [],
    }
  );
  
  // Update clientId if it was provided in query string (handles case where clients haven't loaded yet)
  useEffect(() => {
    if (isNewOrder && clientIdFromQuery && formData.clientId !== clientIdFromQuery && !existingOrder) {
      setFormData(prev => ({ ...prev, clientId: clientIdFromQuery }));
    }
  }, [isNewOrder, clientIdFromQuery, formData.clientId, existingOrder]);
  
  const [showJobPicker, setShowJobPicker] = useState(false);
  const [showPresetPicker, setShowPresetPicker] = useState(false);
  const [jobSearchQuery, setJobSearchQuery] = useState('');
  const [presetSearchQuery, setPresetSearchQuery] = useState('');
  const [clientSearchQuery, setClientSearchQuery] = useState('');
  const [clientPickerOpen, setClientPickerOpen] = useState(false);
  const [editingJobId, setEditingJobId] = useState<string | null>(null);
  const [editingJobName, setEditingJobName] = useState('');
  const [focusedPriceInputs, setFocusedPriceInputs] = useState<Set<string>>(new Set());
  const [showUnsavedChangesDialog, setShowUnsavedChangesDialog] = useState(false);
  const [pendingNavigation, setPendingNavigation] = useState<{ page: string; id?: string } | null>(null);
  const [showDocumentDialog, setShowDocumentDialog] = useState(false);
  const [pendingDocumentAction, setPendingDocumentAction] = useState<(() => Promise<void>) | null>(null);
  
  // Resizable column width state
  const [jobColumnWidth, setJobColumnWidth] = useState(() => {
    const saved = localStorage.getItem('orderDetail_jobColumnWidth');
    return saved ? parseInt(saved, 10) : 300; // Default 300px
  });
  const [isResizing, setIsResizing] = useState(false);
  
  const selectedClient = useMemo(() => 
    formData.clientId ? clients.find(c => c.id === formData.clientId) : null,
    [clients, formData.clientId]
  );
  
  const totals = useMemo(() => 
    getOrderTotals(formData as Order),
    [formData]
  );
  
  const filteredJobs = useMemo(() => {
    if (!jobSearchQuery.trim()) return [];
    const query = jobSearchQuery.toLowerCase().trim();
    const queryWords = query.split(/\s+/).filter(word => word.length > 0);
    
    return jobTemplates
      .filter(job => {
        const searchableText = `${job.name} ${job.description} ${job.category}`.toLowerCase();
        // Check if all query words appear in the searchable text
        return queryWords.every(word => searchableText.includes(word));
      })
      .slice(0, 10);
  }, [jobTemplates, jobSearchQuery]);
  
  const filteredPresets = useMemo(() => {
    if (!presetSearchQuery.trim()) return jobPresets;
    const query = presetSearchQuery.toLowerCase().trim();
    const queryWords = query.split(/\s+/).filter(word => word.length > 0);
    
    return jobPresets.filter(preset => {
      const searchableText = `${preset.name} ${preset.description} ${preset.category}`.toLowerCase();
      // Check if all query words appear in the searchable text
      return queryWords.every(word => searchableText.includes(word));
    });
  }, [jobPresets, presetSearchQuery]);

  const filteredClients = useMemo(() => {
    if (!clientSearchQuery.trim()) return [];
    const query = clientSearchQuery.toLowerCase().trim();
    const queryWords = query.split(/\s+/).filter(word => word.length > 0);
    
    return clients.filter(client => {
      const searchableText = `${client.name} ${client.company} ${client.email} ${client.phone}`.toLowerCase();
      // Check if all query words appear in the searchable text
      return queryWords.every(word => searchableText.includes(word));
    });
  }, [clients, clientSearchQuery]);
  
  // Limit displayed clients to 5
  const displayedClients = useMemo(() => {
    return filteredClients.slice(0, 5);
  }, [filteredClients]);
  
  const hasMoreClients = filteredClients.length > 5;
  
  // Check if order is saved (exists in orders list or has a real ID)
  const isOrderSaved = useMemo(() => {
    // If we have a valid ID (not 'new') and it exists in orders list, it's saved
    if (formData.id && formData.id !== 'new') {
      return orders.some(o => o.id === formData.id);
    }
    return false;
  }, [formData.id, orders]);
  
  // Check if order has unsaved changes
  const hasUnsavedChanges = useMemo(() => {
    // If order is saved, no unsaved changes
    if (isOrderSaved) return false;
    
    // For new orders, check if any data has been entered
    if (isNewOrder) {
      return !!(formData.clientId || (formData.jobs && formData.jobs.length > 0));
    }
    
    // For existing orders that aren't saved yet, there are unsaved changes
    return true;
  }, [isNewOrder, formData.clientId, formData.jobs, isOrderSaved]);
  
  const handleSave = async () => {
    if (!formData.clientId) {
      toast.error(t('orderDetail.selectClientRequired') || 'Please select a client');
      return;
    }
    
    try {
      const orderData: Order = {
        id: isNewOrder ? generateOrderId() : (existingOrder?.id || formData.id || ''),
        clientId: formData.clientId,
        status: formData.status as OrderStatus || 'proposal',
        createdAt: existingOrder?.createdAt || new Date(),
        updatedAt: new Date(),
        taxRate: formData.taxRate || 8.5,
        globalMarkup: formData.globalMarkup || 0,
        currency: formData.currency || 'USD',
        orderType: formData.orderType || '',
        orderTitle: formData.orderTitle || '',
        jobs: formData.jobs || [],
      };
      
      if (isNewOrder) {
        await addOrder(orderData);
        toast.success(t('orderDetail.orderCreatedSuccess'));
        // Update formData with the new order ID before navigation
        setFormData({ ...formData, ...orderData });
        onNavigate('order-detail', orderData.id);
      } else {
        await updateOrder(orderData.id, orderData);
        toast.success(t('orderDetail.orderUpdatedSuccess'));
        // Update formData to reflect saved state
        setFormData({ ...formData, ...orderData });
      }
    } catch (error: any) {
      console.error('Error saving order:', error);
      const errorMessage = error?.message || error?.error?.message || t('orderDetail.saveOrderFailed');
      toast.error(errorMessage);
    }
  };
  
  // Handle navigation with unsaved changes warning
  const handleNavigate = useCallback((page: string, id?: string) => {
    if (hasUnsavedChanges) {
      setPendingNavigation({ page, id });
      setShowUnsavedChangesDialog(true);
      return;
    }
    onNavigate(page, id);
  }, [hasUnsavedChanges, onNavigate]);
  
  const handleConfirmNavigation = () => {
    if (pendingNavigation) {
      onNavigate(pendingNavigation.page, pendingNavigation.id);
      setPendingNavigation(null);
    }
    setShowUnsavedChangesDialog(false);
  };
  
  const handleSaveAndLeave = async () => {
    if (!formData.clientId) {
      toast.error(t('orderDetail.selectClientRequired') || 'Please select a client');
      setShowUnsavedChangesDialog(false);
      return;
    }
    
    try {
      // Check if order already exists in the database
      const orderExists = formData.id && formData.id !== 'new' && orders.some(o => o.id === formData.id);
      
      const orderData: Order = {
        id: orderExists ? formData.id! : (isNewOrder ? generateOrderId() : (existingOrder?.id || formData.id || '')),
        clientId: formData.clientId,
        status: formData.status as OrderStatus || 'proposal',
        createdAt: existingOrder?.createdAt || new Date(),
        updatedAt: new Date(),
        taxRate: formData.taxRate || 8.5,
        globalMarkup: formData.globalMarkup || 0,
        currency: formData.currency || 'USD',
        orderType: formData.orderType || '',
        orderTitle: formData.orderTitle || '',
        jobs: formData.jobs || [],
      };
      
      if (orderExists) {
        // Order already exists, update it
        await updateOrder(orderData.id, orderData);
        toast.success(t('orderDetail.orderUpdatedSuccess'));
      } else if (isNewOrder) {
        // New order, create it
        await addOrder(orderData);
        toast.success(t('orderDetail.orderCreatedSuccess'));
      } else {
        // Existing order (not in list yet), update it
        await updateOrder(orderData.id, orderData);
        toast.success(t('orderDetail.orderUpdatedSuccess'));
      }
      
      // Navigate to pending navigation or saved order
      if (pendingNavigation) {
        onNavigate(pendingNavigation.page, pendingNavigation.id);
      } else if (isNewOrder && !orderExists) {
        onNavigate('order-detail', orderData.id);
      }
      
      setPendingNavigation(null);
      setShowUnsavedChangesDialog(false);
    } catch (error: any) {
      console.error('Error saving order:', error);
      const errorMessage = error?.message || error?.error?.message || t('orderDetail.saveOrderFailed');
      toast.error(errorMessage);
    }
  };
  
  const handleCancelNavigation = () => {
    setPendingNavigation(null);
    setShowUnsavedChangesDialog(false);
  };
  
  const handleAddJob = (jobId: string) => {
    const job = jobTemplates.find(j => j.id === jobId);
    if (!job) return;
    
    const newJob: OrderJob = {
      id: generateId('job'),
      jobId: job.id,
      jobName: job.name,
      description: job.description,
      quantity: 1,
      unitPrice: job.unitPrice,
      lineMarkup: formData.globalMarkup || 0,
      taxApplicable: job.defaultTax,
      position: formData.jobs?.length || 0,
    };
    
    setFormData({
      ...formData,
      jobs: [...(formData.jobs || []), newJob],
    });
    
    toast.success(t('orderDetail.jobAdded', { jobName: job.name }) || `Added ${job.name}`);
  };
  
  const handleAddPreset = (presetId: string) => {
    const preset = jobPresets.find(p => p.id === presetId);
    if (!preset) return;
    
    const newJobs: OrderJob[] = preset.jobs.map((presetJob, index) => {
      const job = jobTemplates.find(j => j.id === presetJob.jobId);
      if (!job) return null;
      
      return {
        id: generateId('job'),
        jobId: job.id,
        jobName: job.name,
        description: job.description,
        quantity: presetJob.defaultQty,
        unitPrice: job.unitPrice,
        lineMarkup: formData.globalMarkup || 0,
        taxApplicable: job.defaultTax,
        position: (formData.jobs?.length || 0) + index,
      };
    }).filter(Boolean) as OrderJob[];
    
    setFormData({
      ...formData,
      jobs: [...(formData.jobs || []), ...newJobs],
    });
    
    setShowPresetPicker(false);
    toast.success(t('orderDetail.presetAdded', { presetName: preset.name }) || `Added ${preset.name} preset`);
  };
  
  const handleRemoveJob = (jobId: string) => {
    setFormData({
      ...formData,
      jobs: formData.jobs?.filter(j => j.id !== jobId) || [],
    });
  };
  
  const handleDuplicateJob = (jobId: string) => {
    const jobToDuplicate = formData.jobs?.find(j => j.id === jobId);
    if (!jobToDuplicate) return;
    
    const duplicatedJob: OrderJob = {
      ...jobToDuplicate,
      id: generateId('order-job'),
    };
    
    setFormData({
      ...formData,
      jobs: [...(formData.jobs || []), duplicatedJob],
    });
  };
  
  const handleStartEditJobName = (jobId: string) => {
    const job = formData.jobs?.find(j => j.id === jobId);
    if (job) {
      setEditingJobId(jobId);
      setEditingJobName(job.jobName);
    }
  };
  
  const handleSaveJobName = (jobId: string) => {
    if (editingJobName.trim()) {
      handleUpdateJob(jobId, { jobName: editingJobName.trim() });
    }
    setEditingJobId(null);
    setEditingJobName('');
  };
  
  const handleCancelEditJobName = () => {
    setEditingJobId(null);
    setEditingJobName('');
  };
  
  // Document generation handlers
  const handleGenerateDocument = async (action: () => Promise<void>) => {
    if (!isOrderSaved) {
      setPendingDocumentAction(() => action);
      setShowDocumentDialog(true);
      return;
    }
    await action();
  };
  
  const handleCreateDocumentAnyway = async () => {
    setShowDocumentDialog(false);
    if (pendingDocumentAction) {
      await pendingDocumentAction();
      setPendingDocumentAction(null);
    }
  };
  
  const handleSaveAndCreateDocument = async () => {
    setShowDocumentDialog(false);
    
    // Save the order first
    if (!formData.clientId) {
      toast.error(t('orderDetail.selectClientRequired') || 'Please select a client');
      setPendingDocumentAction(null);
      return;
    }
    
    try {
      const orderData: Order = {
        id: isNewOrder ? generateOrderId() : (existingOrder?.id || formData.id || ''),
        clientId: formData.clientId,
        status: (formData.status || 'proposal') as OrderStatus,
        orderType: formData.orderType || '',
        orderTitle: formData.orderTitle || '',
        jobs: formData.jobs || [],
        createdAt: existingOrder?.createdAt || new Date(),
        updatedAt: new Date(),
        taxRate: formData.taxRate || 8.5,
        globalMarkup: formData.globalMarkup || 0,
        currency: formData.currency || 'USD',
      };
      
      if (isNewOrder) {
        await addOrder(orderData);
        toast.success(t('orderDetail.orderCreatedSuccess'));
        // Update formData with the new order ID and all order data
        // This ensures the order is recognized as saved
        setFormData({ ...formData, ...orderData });
      } else {
        await updateOrder(orderData.id, orderData);
        toast.success(t('orderDetail.orderUpdatedSuccess'));
        // Update formData to reflect saved state
        setFormData({ ...formData, ...orderData });
      }
      
      // Small delay to ensure orders list updates and state propagates
      await new Promise(resolve => setTimeout(resolve, 300));
      
      // Now generate the document
      if (pendingDocumentAction) {
        await pendingDocumentAction();
        setPendingDocumentAction(null);
      }
    } catch (error) {
      console.error('Error saving order:', error);
      toast.error(t('orderDetail.saveOrderFailed'));
      setPendingDocumentAction(null);
    }
  };
  
  const handleCancelDocumentDialog = () => {
    setShowDocumentDialog(false);
    setPendingDocumentAction(null);
  };
  
  // Number formatting helpers
  const formatNumber = (value: number, locale?: string): string => {
    const finalLocale = locale || (i18n.language === 'ru' ? 'ru-RU' : 'en-US');
    return new Intl.NumberFormat(finalLocale, {
      minimumFractionDigits: 0,
      maximumFractionDigits: 2,
    }).format(value);
  };
  
  const parseFormattedNumber = (value: string): number => {
    // Remove all non-digit characters except decimal point
    const cleaned = value.replace(/[^\d.,]/g, '');
    // Replace comma with dot for parsing
    const normalized = cleaned.replace(',', '.');
    return parseFloat(normalized) || 0;
  };
  
  const handlePriceFocus = (jobId: string) => {
    setFocusedPriceInputs(prev => new Set(prev).add(jobId));
  };
  
  const handlePriceBlur = (jobId: string, currentValue: string) => {
    const parsed = parseFormattedNumber(currentValue);
    handleUpdateJob(jobId, { unitPrice: parsed });
    setFocusedPriceInputs(prev => {
      const next = new Set(prev);
      next.delete(jobId);
      return next;
    });
  };
  
  // Column resize handlers
  const handleResizeStart = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsResizing(true);
    
    // Add visual feedback
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';
    
    const startX = e.clientX;
    const startWidth = jobColumnWidth;
    let currentWidth = startWidth;
    
    const handleMouseMove = (e: MouseEvent) => {
      const diff = e.clientX - startX;
      currentWidth = Math.max(150, Math.min(800, startWidth + diff)); // Min 150px, max 800px
      setJobColumnWidth(currentWidth);
    };
    
    const handleMouseUp = () => {
      setIsResizing(false);
      localStorage.setItem('orderDetail_jobColumnWidth', currentWidth.toString());
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
    };
    
    document.addEventListener('mousemove', handleMouseMove);
    document.addEventListener('mouseup', handleMouseUp);
  }, [jobColumnWidth]);
  
  const handleUpdateJob = (jobId: string, updates: Partial<OrderJob>) => {
    setFormData({
      ...formData,
      jobs: formData.jobs?.map(j => 
        j.id === jobId ? { ...j, ...updates } : j
      ) || [],
    });
  };
  
  const handleApplyGlobalMarkup = () => {
    if (!formData.jobs) return;
    
    setFormData({
      ...formData,
      jobs: formData.jobs.map(j => ({
        ...j,
        lineMarkup: formData.globalMarkup || 0,
      })),
    });
    
    toast.success(t('orderDetail.markupApplied'));
  };
  
  if (!isNewOrder && !existingOrder) {
    return (
      <div className="text-center py-12">
        <p className="text-[#7C8085] mb-4">Order not found</p>
        <button
          onClick={() => onNavigate('orders')}
          className="px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors cursor-pointer"
        >
          Back to Orders
        </button>
      </div>
    );
  }
  
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <button
            onClick={() => handleNavigate('orders')}
            className="p-2 hover:bg-[#E4E7E7] rounded-lg transition-colors cursor-pointer"
            aria-label="Back to orders"
          >
            <ArrowLeft size={20} />
          </button>
          <div>
            <h1 className="text-[#1E2025] mb-1">
              {isNewOrder ? 'New Order' : formData.id}
            </h1>
            {selectedClient && (
              <button
                onClick={() => onNavigate('client-detail', selectedClient.id)}
                className="text-left cursor-pointer"
                onMouseEnter={(e) => {
                  const p = e.currentTarget.querySelector('p');
                  const spans = e.currentTarget.querySelectorAll('span');
                  if (p) p.style.textDecoration = 'underline';
                  spans.forEach(span => {
                    span.style.color = '#1F744F';
                  });
                }}
                onMouseLeave={(e) => {
                  const p = e.currentTarget.querySelector('p');
                  const spans = e.currentTarget.querySelectorAll('span');
                  if (p) p.style.textDecoration = 'none';
                  spans.forEach(span => {
                    span.style.color = '';
                  });
                  // Reset company-only case
                  if (spans.length === 0 && p) {
                    p.style.color = '';
                  }
                }}
              >
                {selectedClient.name && selectedClient.name !== 'Unknown' && selectedClient.name.trim() !== '' ? (
                  selectedClient.company && selectedClient.company.trim() !== '' ? (
                    <p className="text-[#555A60]">
                      <span className="transition-colors">{selectedClient.name}</span>
                      {' · '}
                      <span className="transition-colors">{selectedClient.company}</span>
                    </p>
                  ) : (
                    <p className="text-[#555A60] transition-all">{selectedClient.name}</p>
                  )
                ) : (
                  selectedClient.company && selectedClient.company.trim() !== '' ? (
                    <p className="text-[#555A60] transition-all">{selectedClient.company}</p>
                  ) : null
                )}
              </button>
            )}
          </div>
        </div>
        <button
          onClick={handleSave}
          className="flex items-center gap-2 px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors cursor-pointer"
        >
          <Save size={20} aria-hidden="true" />
          {isNewOrder ? t('orderDetail.createOrder') : t('common.saveChanges')}
        </button>
      </div>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Content - Left 2 columns */}
        <div className="lg:col-span-2 space-y-6">
          {/* Order Info Card */}
          <div className="bg-white rounded-xl border border-[#E4E7E7] p-6">
            <h2 className="text-[#1E2025] mb-4">{t('orderDetail.orderInformation')}</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="client">{t('orderDetail.clientRequired')}</Label>
                <Popover open={clientPickerOpen} onOpenChange={setClientPickerOpen}>
                  <PopoverTrigger asChild>
                    <Button
                      id="client"
                      variant="outline"
                      role="combobox"
                      className="w-full justify-between text-left font-normal h-9"
                    >
                      {selectedClient 
                        ? (() => {
                            const hasName = selectedClient.name && selectedClient.name !== 'Unknown' && selectedClient.name.trim() !== '';
                            const hasCompany = selectedClient.company && selectedClient.company.trim() !== '';
                            if (hasName && hasCompany) {
                              return `${selectedClient.name} - ${selectedClient.company}`;
                            } else if (hasName) {
                              return selectedClient.name;
                            } else if (hasCompany) {
                              return selectedClient.company;
                            }
                            return t('orderDetail.selectClient');
                          })()
                        : t('orderDetail.selectClient')}
                      <Search className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent 
                    className="!w-[400px] !max-w-[400px] !min-w-[400px] p-0 overflow-hidden" 
                    align="start"
                    style={{ width: '400px', maxWidth: '400px', minWidth: '400px' }}
                  >
                    <div className="w-full overflow-hidden" style={{ width: '400px', maxWidth: '400px', boxSizing: 'border-box' }}>
                      <div className="p-4 border-b border-[#E4E7E7]">
                        <div className="relative">
                          <Search 
                            className="absolute left-3 top-1/2 -translate-y-1/2 text-[#7C8085]" 
                            size={18}
                            aria-hidden="true"
                          />
                          <Input
                            type="search"
                            placeholder={t('orderDetail.searchClientsPlaceholder') || 'Search clients...'}
                            value={clientSearchQuery}
                            onChange={(e) => setClientSearchQuery(e.target.value)}
                            className="pl-10 w-full"
                            style={{ maxWidth: '100%', boxSizing: 'border-box' }}
                            aria-label={t('orderDetail.searchClientsLabel') || 'Search clients'}
                          />
                        </div>
                      </div>
                      <div className="max-h-[300px] overflow-y-auto w-full" style={{ width: '400px', maxWidth: '400px', boxSizing: 'border-box' }}>
                        {filteredClients.length === 0 ? (
                          <div className="p-4 text-center text-[#7C8085]">
                            {clientSearchQuery.trim() 
                              ? (t('orderDetail.noClientsFound') || 'No clients found')
                              : (t('orderDetail.startTypingToSearchClients') || 'Start typing to search for clients')}
                          </div>
                        ) : (
                          <>
                            <div className="p-2">
                              {displayedClients.map(client => (
                              <button
                                key={client.id}
                                onClick={() => {
                                  setFormData({ ...formData, clientId: client.id });
                                  setClientPickerOpen(false);
                                  setClientSearchQuery('');
                                }}
                                className="w-full p-3 text-left rounded-lg hover:bg-[#F7F8F8] transition-colors cursor-pointer overflow-hidden"
                                style={{ maxWidth: '100%', boxSizing: 'border-box' }}
                              >
                                {client.company && client.company.trim() !== '' ? (
                                  <>
                                    <p className="text-[#1E2025] font-medium truncate">
                                      {client.company}
                                    </p>
                                    {client.name && client.name !== 'Unknown' && client.name.trim() !== '' && (
                                      <p className="text-[#7C8085] text-sm truncate">{client.name}</p>
                                    )}
                                  </>
                                ) : (
                                  client.name && client.name !== 'Unknown' && client.name.trim() !== '' && (
                                    <p className="text-[#1E2025] font-medium truncate">{client.name}</p>
                                  )
                                )}
                                {client.email && typeof client.email === 'string' && client.email.trim() !== '' && (
                                  <p className="text-[#7C8085] text-sm truncate">{client.email}</p>
                                )}
                              </button>
                            ))}
                            </div>
                            {hasMoreClients && (
                              <div className="p-3 border-t border-[#E4E7E7] text-center">
                                <p className="text-[#7C8085] text-sm">
                                  {t('orderDetail.moreClientsAvailable', { count: filteredClients.length - 5 }) || `Continue typing to see ${filteredClients.length - 5} more result${filteredClients.length - 5 === 1 ? '' : 's'}`}
                                </p>
                              </div>
                            )}
                          </>
                        )}
                      </div>
                    </div>
                  </PopoverContent>
                </Popover>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="status">{t('orderDetail.status')}</Label>
                <Select
                  value={formData.status || 'proposal'}
                  onValueChange={(value) => setFormData({ ...formData, status: value as OrderStatus })}
                >
                  <SelectTrigger id="status">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="proposal">{t('orders.proposal')}</SelectItem>
                    <SelectItem value="in-progress">{t('orders.inProgress')}</SelectItem>
                    <SelectItem value="completed">{t('orders.completed')}</SelectItem>
                    <SelectItem value="canceled">{t('orders.canceled')}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2 md:col-span-2">
                <Label htmlFor="orderType">{t('orderDetail.orderType')}</Label>
                <Select
                  value={formData.orderType || ''}
                  onValueChange={(value) => setFormData({ ...formData, orderType: value })}
                >
                  <SelectTrigger id="orderType">
                    <SelectValue placeholder={t('orderDetail.orderTypePlaceholder')} />
                  </SelectTrigger>
                  <SelectContent>
                    {ORDER_TYPES.map((type) => (
                      <SelectItem key={type.value} value={type.value}>
                        {getOrderTypeLabel(type.value)}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2 md:col-span-2">
                <Label htmlFor="orderTitle">{t('orderDetail.orderTitle')}</Label>
                <Textarea
                  id="orderTitle"
                  value={formData.orderTitle || ''}
                  onChange={(e) => setFormData({ ...formData, orderTitle: e.target.value })}
                  rows={2}
                  placeholder={t('orderDetail.orderTitlePlaceholder')}
                />
              </div>
            </div>
          </div>
          
          {/* Line Items */}
          <div className="bg-white rounded-xl border border-[#E4E7E7]">
            <div className="px-6 py-4 border-b border-[#E4E7E7] flex items-center justify-between">
              <h2 className="text-[#1E2025]">{t('orderDetail.lineItems')}</h2>
              <div className="flex gap-2">
                <button
                  onClick={() => {
                    if (showPresetPicker) {
                      setPresetSearchQuery('');
                    }
                    setShowPresetPicker(!showPresetPicker);
                    if (!showPresetPicker) {
                      setShowJobPicker(false);
                      setJobSearchQuery('');
                    }
                  }}
                  className="flex items-center gap-2 px-3 py-2 bg-[#E4E7E7] text-[#1E2025] rounded-lg hover:bg-[#D2D6D6] transition-colors"
                >
                  <Layers size={18} aria-hidden="true" />
                  {t('orderDetail.addPreset')}
                </button>
                <button
                  onClick={() => {
                    if (showJobPicker) {
                      setJobSearchQuery('');
                    }
                    setShowJobPicker(!showJobPicker);
                    if (!showJobPicker) {
                      setShowPresetPicker(false);
                      setPresetSearchQuery('');
                    }
                  }}
                  className="flex items-center gap-2 px-3 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors"
                >
                  <Plus size={18} aria-hidden="true" />
                  {t('orderDetail.addJob')}
                </button>
              </div>
            </div>
            
            {/* Job Picker */}
            {showJobPicker && (
              <div className="px-6 py-4 border-b border-[#E4E7E7] bg-[#F7F8F8]">
                <h3 className="text-[#555A60] mb-3">{t('orderDetail.selectJobToAdd')}</h3>
                <div className="relative mb-3">
                  <Search 
                    className="absolute left-3 top-1/2 -translate-y-1/2 text-[#7C8085]" 
                    size={18}
                    aria-hidden="true"
                  />
                  <Input
                    type="search"
                    placeholder={t('orderDetail.searchJobsPlaceholder')}
                    value={jobSearchQuery}
                    onChange={(e) => setJobSearchQuery(e.target.value)}
                    className="pl-10"
                    aria-label={t('orderDetail.searchJobsLabel')}
                  />
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2 max-h-60 overflow-y-auto">
                  {filteredJobs.length === 0 ? (
                    <div className="col-span-2 text-center py-4 text-[#7C8085]">
                      {jobSearchQuery.trim() ? t('orderDetail.noJobsFound') : t('orderDetail.startTypingToSearch')}
                    </div>
                  ) : (
                    filteredJobs.map(job => (
                      <button
                        key={job.id}
                        onClick={() => {
                          handleAddJob(job.id);
                          setShowJobPicker(false);
                          setJobSearchQuery('');
                        }}
                        className="p-3 bg-white rounded-lg border border-[#E4E7E7] hover:border-[#1F744F] transition-colors text-left cursor-pointer"
                      >
                        <p className="text-[#1E2025] mb-1">{job.name}</p>
                        <p className="text-[#1F744F]">
                          {formatCurrency(job.unitPrice)} / {job.unitOfMeasure}
                        </p>
                      </button>
                    ))
                  )}
                </div>
              </div>
            )}
            
            {/* Preset Picker */}
            {showPresetPicker && (
              <div className="px-6 py-4 border-b border-[#E4E7E7] bg-[#F7F8F8]">
                <h3 className="text-[#555A60] mb-3">{t('orderDetail.selectPresetToAdd')}</h3>
                <div className="relative mb-3">
                  <Search 
                    className="absolute left-3 top-1/2 -translate-y-1/2 text-[#7C8085]" 
                    size={18}
                    aria-hidden="true"
                  />
                  <Input
                    type="search"
                    placeholder={t('orderDetail.searchPresetsPlaceholder')}
                    value={presetSearchQuery}
                    onChange={(e) => setPresetSearchQuery(e.target.value)}
                    className="pl-10"
                    aria-label={t('orderDetail.searchPresetsLabel')}
                  />
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2 max-h-60 overflow-y-auto">
                  {filteredPresets.length === 0 ? (
                    <div className="col-span-2 text-center py-4 text-[#7C8085]">
                      {presetSearchQuery.trim() ? t('orderDetail.noPresetsFound') : t('orderDetail.noPresetsAvailable')}
                    </div>
                  ) : (
                    filteredPresets.map(preset => (
                      <button
                        key={preset.id}
                        onClick={() => {
                          handleAddPreset(preset.id);
                          setShowPresetPicker(false);
                          setPresetSearchQuery('');
                        }}
                        className="p-3 bg-white rounded-lg border border-[#E4E7E7] hover:border-[#1F744F] transition-colors text-left"
                      >
                        <p className="text-[#1E2025] mb-1">{preset.name}</p>
                        <p className="text-[#7C8085] mb-1 line-clamp-2">{preset.description}</p>
                        <p className="text-[#555A60]">{preset.jobs.length} {t('orderDetail.jobsCount')}</p>
                      </button>
                    ))
                  )}
                </div>
              </div>
            )}
            
            {/* Line Items Table */}
            {!formData.jobs || formData.jobs.length === 0 ? (
              <div className="px-6 py-12 text-center">
                <p className="text-[#7C8085] mb-4">{t('orderDetail.noLineItems')}</p>
                <p className="text-[#7C8085]">{t('orderDetail.noLineItemsDescription')}</p>
              </div>
            ) : (
              <div className="overflow-x-auto relative">
                <div 
                  className="absolute right-[120px] top-0 bottom-0 w-12 pointer-events-none z-20"
                  style={{
                    background: 'linear-gradient(to right, rgba(255,255,255,0) 0%, rgba(255,255,255,0.8) 50%, rgba(255,255,255,1) 100%)'
                  }}
                />
                <table className="w-full" style={{ borderCollapse: 'separate', borderSpacing: 0 }}>
                  <thead>
                    <tr>
                      <th 
                        className={`px-6 py-3 text-left text-[#555A60] border-b border-[#E4E7E7] border-r relative select-none cursor-col-resize overflow-hidden group ${isResizing ? 'bg-[#F7F8F8]' : ''}`}
                        style={{ 
                          width: `${jobColumnWidth}px`, 
                          minWidth: `${jobColumnWidth}px`, 
                          maxWidth: `${jobColumnWidth}px`,
                          borderRightColor: isResizing ? '#1F744F' : '#D2D6D6',
                          borderRightWidth: isResizing ? '2px' : '1px'
                        }}
                        onMouseDown={handleResizeStart}
                        onMouseEnter={(e) => {
                          if (!isResizing) {
                            e.currentTarget.style.borderRightColor = '#1F744F';
                            e.currentTarget.style.borderRightWidth = '2px';
                          }
                        }}
                        onMouseLeave={(e) => {
                          if (!isResizing) {
                            e.currentTarget.style.borderRightColor = '#D2D6D6';
                            e.currentTarget.style.borderRightWidth = '1px';
                          }
                        }}
                        title="Drag right edge to resize"
                      >
                        {t('orderDetail.job')}
                      </th>
                      <th className="px-6 py-3 text-left text-[#555A60] border-b border-[#E4E7E7]">{t('orderDetail.qty')}</th>
                      <th className="px-6 py-3 text-left text-[#555A60] border-b border-[#E4E7E7]">{t('orderDetail.unitPrice')}</th>
                      <th className="px-6 py-3 text-left text-[#555A60] border-b border-[#E4E7E7]">{t('orderDetail.markup')}</th>
                      <th className="px-6 py-3 text-right text-[#555A60] border-b border-[#E4E7E7]">{t('orderDetail.lineTotal')}</th>
                      <th 
                        className="px-6 py-3 text-right text-[#555A60] border-b border-[#E4E7E7] sticky right-0 z-10 bg-white"
                        style={{ 
                          position: 'sticky', 
                          right: 0, 
                          zIndex: 10, 
                          minWidth: '120px',
                          background: 'linear-gradient(to right, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 20px, rgba(255,255,255,1) 100%)'
                        }}
                      >
                        {t('orderDetail.actions')}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {formData.jobs.map(job => {
                      const lineTotal = calculateLineTotal(job);
                      
                      return (
                        <tr key={job.id}>
                          <td 
                            className="px-6 py-4 border-b border-[#E4E7E7] border-r border-[#D2D6D6] overflow-hidden"
                            style={{ width: `${jobColumnWidth}px`, minWidth: `${jobColumnWidth}px`, maxWidth: `${jobColumnWidth}px` }}
                          >
                            {editingJobId === job.id ? (
                              <div className="flex items-center gap-2">
                                <Input
                                  value={editingJobName}
                                  onChange={(e) => setEditingJobName(e.target.value)}
                                  onKeyDown={(e) => {
                                    if (e.key === 'Enter') {
                                      handleSaveJobName(job.id);
                                    } else if (e.key === 'Escape') {
                                      handleCancelEditJobName();
                                    }
                                  }}
                                  className="flex-1 min-w-[200px]"
                                  autoFocus
                                />
                                <button
                                  onClick={() => handleSaveJobName(job.id)}
                                  className="p-1.5 text-[#1F744F] hover:bg-[#E8F5E9] rounded transition-colors cursor-pointer"
                                  aria-label="Save"
                                >
                                  <Check size={16} />
                                </button>
                                <button
                                  onClick={handleCancelEditJobName}
                                  className="p-1.5 text-[#7C8085] hover:bg-[#F7F8F8] rounded transition-colors cursor-pointer"
                                  aria-label="Cancel"
                                >
                                  <X size={16} />
                                </button>
                              </div>
                            ) : (
                              <div className="flex items-center gap-2 group min-w-0">
                                <p 
                                  className="text-[#1E2025] cursor-pointer hover:text-[#1F744F] transition-colors whitespace-nowrap truncate flex-1 min-w-0"
                                  onClick={() => handleStartEditJobName(job.id)}
                                  title={job.jobName}
                                >
                                  {job.jobName}
                                </p>
                                <button
                                  onClick={() => handleStartEditJobName(job.id)}
                                  className="p-1 opacity-0 group-hover:opacity-100 text-[#7C8085] hover:text-[#1F744F] hover:bg-[#F7F8F8] rounded transition-all cursor-pointer"
                                  aria-label={t('orderDetail.editJobName')}
                                >
                                  <Edit2 size={14} />
                                </button>
                              </div>
                            )}
                          </td>
                          <td className="px-6 py-4 border-b border-[#E4E7E7]">
                            <Input
                              type="number"
                              min="0"
                              step="1"
                              value={job.quantity}
                              onChange={(e) => handleUpdateJob(job.id, { 
                                quantity: parseInt(e.target.value, 10) || 0 
                              })}
                              onWheel={(e) => e.currentTarget.blur()}
                              onKeyDown={(e) => {
                                // Prevent decimal point and 'e', 'E', '+', '-' keys
                                if (['e', 'E', '+', '-', '.'].includes(e.key)) {
                                  e.preventDefault();
                                }
                              }}
                              className="w-20"
                              aria-label={`Quantity for ${job.jobName}`}
                            />
                          </td>
                          <td className="px-6 py-4 border-b border-[#E4E7E7]">
                            <Input
                              type="text"
                              inputMode="decimal"
                              value={focusedPriceInputs.has(job.id) 
                                ? (job.unitPrice === 0 ? '' : job.unitPrice.toString()) 
                                : (job.unitPrice === 0 ? '' : formatNumber(job.unitPrice))
                              }
                              onChange={(e) => {
                                const parsed = parseFormattedNumber(e.target.value);
                                handleUpdateJob(job.id, { unitPrice: parsed });
                              }}
                              onFocus={() => handlePriceFocus(job.id)}
                              onBlur={(e) => handlePriceBlur(job.id, e.target.value)}
                              className="w-28"
                              aria-label={`Unit price for ${job.jobName}`}
                            />
                          </td>
                          <td className="px-6 py-4 border-b border-[#E4E7E7]">
                            <Input
                              type="number"
                              min="0"
                              step="1"
                              value={job.lineMarkup}
                              onChange={(e) => handleUpdateJob(job.id, { 
                                lineMarkup: parseFloat(e.target.value) || 0 
                              })}
                              onWheel={(e) => e.currentTarget.blur()}
                              className="w-20"
                              aria-label={`Markup for ${job.jobName}`}
                            />
                          </td>
                          <td className="px-6 py-4 text-right border-b border-[#E4E7E7]">
                            <p className="text-[#1E2025]">{formatCurrency(lineTotal)}</p>
                          </td>
                          <td 
                            className="px-6 py-4 text-right border-b border-[#E4E7E7] sticky right-0 z-10 bg-white"
                            data-sticky="true"
                            style={{ 
                              position: 'sticky', 
                              right: 0, 
                              zIndex: 10, 
                              minWidth: '120px',
                              background: 'linear-gradient(to right, rgba(255,255,255,0) 0%, rgba(255,255,255,1) 20px, rgba(255,255,255,1) 100%)'
                            }}
                          >
                            <div className="flex items-center justify-end gap-1">
                              <button
                                onClick={() => handleDuplicateJob(job.id)}
                                className="p-2 text-[#555A60] hover:bg-[#F7F8F8] rounded-lg transition-colors cursor-pointer"
                                aria-label={`Duplicate ${job.jobName}`}
                              >
                                <Copy size={18} />
                              </button>
                              <button
                                onClick={() => handleRemoveJob(job.id)}
                                className="p-2 text-[#E5484D] hover:bg-[#FEE] rounded-lg transition-colors cursor-pointer"
                                aria-label={`Remove ${job.jobName}`}
                              >
                                <Trash2 size={18} />
                              </button>
                            </div>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
        
        {/* Right Sidebar - Pricing Summary */}
        <div className="space-y-6">
          {/* Markup Controls */}
          <div className="bg-white rounded-xl border border-[#E4E7E7] p-6">
            <h3 className="text-[#1E2025] mb-4">{t('orderDetail.markupAndTax')}</h3>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="globalMarkup">{t('orderDetail.globalMarkup')}</Label>
                <Input
                  id="globalMarkup"
                  type="number"
                  min="0"
                  step="1"
                  value={formData.globalMarkup || 0}
                  onChange={(e) => setFormData({ 
                    ...formData, 
                    globalMarkup: parseFloat(e.target.value) || 0 
                  })}
                  onWheel={(e) => e.currentTarget.blur()}
                />
              </div>
              
              <button
                onClick={handleApplyGlobalMarkup}
                className="w-full px-4 py-2 bg-[#E4E7E7] text-[#1E2025] rounded-lg hover:bg-[#D2D6D6] transition-colors"
                disabled={!formData.jobs || formData.jobs.length === 0}
              >
                {t('orderDetail.applyToAllJobs')}
              </button>
              
              <div className="space-y-2">
                <Label htmlFor="taxRate">{t('orderDetail.taxRate')}</Label>
                <Input
                  id="taxRate"
                  type="number"
                  min="0"
                  step="0.1"
                  value={formData.taxRate || 0}
                  onChange={(e) => setFormData({ 
                    ...formData, 
                    taxRate: parseFloat(e.target.value) || 0 
                  })}
                  onWheel={(e) => e.currentTarget.blur()}
                />
              </div>
            </div>
          </div>
          
          {/* Pricing Summary */}
          <div className="bg-white rounded-xl border border-[#E4E7E7] p-6">
            <h3 className="text-[#1E2025] mb-4">{t('orderDetail.orderSummary')}</h3>
            <div className="space-y-3">
              <div className="flex items-center justify-between text-[#555A60]">
                <span>{t('orderDetail.subtotal')}</span>
                <span>{formatCurrency(totals.subtotal)}</span>
              </div>
              <div className="flex items-center justify-between text-[#555A60]">
                <span>{t('orderDetail.tax')} ({formData.taxRate}%)</span>
                <span>{formatCurrency(totals.tax)}</span>
              </div>
              <div className="pt-3 border-t border-[#E4E7E7]">
                <div className="flex items-center justify-between text-[#1E2025]">
                  <span>{t('orderDetail.total')}</span>
                  <span>{formatCurrency(totals.total)}</span>
                </div>
              </div>
            </div>
          </div>
          
          {/* Document Generation */}
          <div className="bg-white rounded-xl border border-[#E4E7E7] p-6">
            <h3 className="text-[#1E2025] mb-4">{t('orderDetail.documents')}</h3>
            <div className="space-y-2">
              <button
                onClick={async () => {
                  if (!formData.clientId || !formData.jobs || formData.jobs.length === 0) {
                    toast.error(t('orderDetail.selectClientAndAddItems') || 'Please select a client and add line items');
                    return;
                  }
                  
                  const client = clients.find(c => c.id === formData.clientId);
                  if (!client) {
                    toast.error(t('orderDetail.clientNotFound') || 'Client not found');
                    return;
                  }
                  
                  await handleGenerateDocument(async () => {
                    setGeneratingInvoice(true);
                    try {
                      const order = formData as Order;
                      const invoiceNumber = generateDocumentNumber(
                        companySettings.invoicePrefix,
                        order.id,
                        order.createdAt || new Date()
                      );
                      await generateInvoice(order, client, companySettings, invoiceNumber);
                      toast.success(t('orderDetail.invoiceGeneratedSuccess'));
                    } catch (error) {
                      console.error('Error generating invoice:', error);
                      toast.error(t('orderDetail.invoiceGenerationFailed'));
                    } finally {
                      setGeneratingInvoice(false);
                    }
                  });
                }}
                className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-[#1F744F] text-white rounded-lg hover:bg-[#165B3C] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={!formData.clientId || !formData.jobs || formData.jobs.length === 0 || generatingInvoice || generatingPO}
              >
                {generatingInvoice ? (
                  <>
                    <Loader2 size={18} className="animate-spin" aria-hidden="true" />
                    {t('orderDetail.generating')}
                  </>
                ) : (
                  <>
                    <FileText size={18} aria-hidden="true" />
                    {t('orderDetail.generateInvoice')}
                  </>
                )}
              </button>
              <button
                onClick={async () => {
                  if (!formData.clientId || !formData.jobs || formData.jobs.length === 0) {
                    toast.error(t('orderDetail.selectClientAndAddItems') || 'Please select a client and add line items');
                    return;
                  }
                  
                  const client = clients.find(c => c.id === formData.clientId);
                  if (!client) {
                    toast.error(t('orderDetail.clientNotFound') || 'Client not found');
                    return;
                  }
                  
                  await handleGenerateDocument(async () => {
                    setGeneratingPO(true);
                    try {
                      const order = formData as Order;
                      const poNumber = generateDocumentNumber(
                        companySettings.poPrefix,
                        order.id,
                        order.createdAt || new Date()
                      );
                      await generatePurchaseOrder(order, client, companySettings, poNumber);
                      toast.success(t('orderDetail.poGeneratedSuccess'));
                    } catch (error) {
                      console.error('Error generating PO:', error);
                      toast.error(t('orderDetail.poGenerationFailed'));
                    } finally {
                      setGeneratingPO(false);
                    }
                  });
                }}
                className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-[#E4E7E7] text-[#1E2025] rounded-lg hover:bg-[#D2D6D6] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={!formData.clientId || !formData.jobs || formData.jobs.length === 0 || generatingInvoice || generatingPO}
              >
                {generatingPO ? (
                  <>
                    <Loader2 size={18} className="animate-spin" aria-hidden="true" />
                    {t('orderDetail.generating')}
                  </>
                ) : (
                  <>
                    <FileText size={18} aria-hidden="true" />
                    {t('orderDetail.generatePO')}
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
      
      {/* Unsaved Changes Confirmation Dialog */}
      <AlertDialog open={showUnsavedChangesDialog} onOpenChange={setShowUnsavedChangesDialog}>
        <AlertDialogContent className="bg-white border border-[#E4E7E7]">
          <AlertDialogHeader>
            <AlertDialogTitle className="text-[#1E2025]">
              {t('orderDetail.unsavedChangesTitle') || 'Unsaved Changes'}
            </AlertDialogTitle>
            <AlertDialogDescription className="text-[#555A60]">
              {t('orderDetail.unsavedChangesWarning') || 'You have unsaved changes. Are you sure you want to leave?'}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter className="flex-col-reverse sm:flex-row gap-2">
            <AlertDialogCancel
              onClick={handleCancelNavigation}
              className="bg-[#E4E7E7] text-[#1E2025] hover:bg-[#D2D6D6] m-0"
            >
              {t('common.cancel') || 'Cancel'}
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleConfirmNavigation}
              className="bg-[#E4E7E7] text-[#1E2025] hover:bg-[#D2D6D6] m-0"
            >
              {t('orderDetail.leaveWithoutSaving') || 'Leave'}
            </AlertDialogAction>
            <AlertDialogAction
              onClick={handleSaveAndLeave}
              className="bg-[#1F744F] text-white hover:bg-[#165B3C] m-0"
            >
              {t('orderDetail.saveAndLeave') || 'Save and Leave'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
      
      {/* Document Generation Confirmation Dialog */}
      <AlertDialog open={showDocumentDialog} onOpenChange={setShowDocumentDialog}>
        <AlertDialogContent className="bg-white border border-[#E4E7E7]">
          <AlertDialogHeader>
            <AlertDialogTitle className="text-[#1E2025]">
              {t('orderDetail.unsavedOrderTitle') || 'Order Not Saved'}
            </AlertDialogTitle>
            <AlertDialogDescription className="text-[#555A60]">
              {t('orderDetail.unsavedOrderWarning') || 'This order has not been saved yet. Would you like to save it before generating the document?'}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter className="flex-col-reverse sm:flex-row gap-2">
            <AlertDialogCancel
              onClick={handleCancelDocumentDialog}
              className="bg-[#E4E7E7] text-[#1E2025] hover:bg-[#D2D6D6] m-0"
            >
              {t('common.cancel') || 'Cancel'}
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={handleCreateDocumentAnyway}
              className="bg-[#E4E7E7] text-[#1E2025] hover:bg-[#D2D6D6] m-0"
            >
              {t('orderDetail.createWithoutSaving') || 'Create Anyway'}
            </AlertDialogAction>
            <AlertDialogAction
              onClick={handleSaveAndCreateDocument}
              className="bg-[#1F744F] text-white hover:bg-[#165B3C] m-0"
            >
              {t('orderDetail.saveAndCreate') || 'Save and Create'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
