-- Batch 1: Simple first names and full names from first line
UPDATE clients SET name = 'Игорь' WHERE id = 'client-xml-10044';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10045';
UPDATE clients SET name = 'Артем' WHERE id = 'client-xml-10046';
UPDATE clients SET name = 'Шпунтов Александр Александрович' WHERE id = 'client-xml-10048';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10052';
UPDATE clients SET name = 'Евгений' WHERE id = 'client-xml-10056';
UPDATE clients SET name = 'Олег' WHERE id = 'client-xml-10064';
UPDATE clients SET name = 'Стрельников Дмитрий' WHERE id = 'client-xml-10070';
UPDATE clients SET name = 'Дима' WHERE id = 'client-xml-10072';
UPDATE clients SET name = 'Олег' WHERE id = 'client-xml-10079';
UPDATE clients SET name = 'Абсалам' WHERE id = 'client-xml-10081';
UPDATE clients SET name = 'Виталий' WHERE id = 'client-xml-10082';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10084';
UPDATE clients SET name = 'Дима' WHERE id = 'client-xml-10085';
UPDATE clients SET name = 'Сергей Васильевич' WHERE id = 'client-xml-10087';
UPDATE clients SET name = 'Полторацкий Александр Николаевич' WHERE id = 'client-xml-10088';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10089';
UPDATE clients SET name = 'Коновалов Дмитрий' WHERE id = 'client-xml-10090';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10093';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10095';
UPDATE clients SET name = 'Юрий Андрееч' WHERE id = 'client-xml-10096';
UPDATE clients SET name = 'Артем' WHERE id = 'client-xml-10097';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10098';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10099';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10100';
UPDATE clients SET name = 'Игорь' WHERE id = 'client-xml-10101';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10102';
UPDATE clients SET name = 'Юрий Солженицин' WHERE id = 'client-xml-10103';
UPDATE clients SET name = 'Иван' WHERE id = 'client-xml-10104';
UPDATE clients SET name = 'Роман' WHERE id = 'client-xml-10107';
UPDATE clients SET name = 'Тарасов Андрей' WHERE id = 'client-xml-10108';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10110';
UPDATE clients SET name = 'Николай' WHERE id = 'client-xml-10112';
UPDATE clients SET name = 'Данила Николаевич' WHERE id = 'client-xml-10114';
UPDATE clients SET name = 'Андрей' WHERE id = 'client-xml-10115';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10116';
UPDATE clients SET name = 'Юрий' WHERE id = 'client-xml-10117';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10118';
UPDATE clients SET name = 'Степанян Торгом Зорикович' WHERE id = 'client-xml-10119';
UPDATE clients SET name = 'Максим Юрьевич' WHERE id = 'client-xml-10120';
UPDATE clients SET name = 'Кучумов Николай Александрович' WHERE id = 'client-xml-10121';
UPDATE clients SET name = 'Константин' WHERE id = 'client-xml-10122';
UPDATE clients SET name = 'Борис' WHERE id = 'client-xml-10123';
UPDATE clients SET name = 'Андрей' WHERE id = 'client-xml-10125';
UPDATE clients SET name = 'Трофимов Максим' WHERE id = 'client-xml-10126';
UPDATE clients SET name = 'Владимир Поликарпов' WHERE id = 'client-xml-10127';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10130';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10132';
UPDATE clients SET name = 'Олег Юрьевич' WHERE id = 'client-xml-10133';
UPDATE clients SET name = 'Владимир' WHERE id = 'client-xml-10134';
UPDATE clients SET name = 'Владимир' WHERE id = 'client-xml-10135';
UPDATE clients SET name = 'Ввсилий' WHERE id = 'client-xml-10136';
UPDATE clients SET name = 'Вадим' WHERE id = 'client-xml-10137';
UPDATE clients SET name = 'Лопатников Александр Алексеевич' WHERE id = 'client-xml-10138';
UPDATE clients SET name = 'Александр Клин' WHERE id = 'client-xml-10140';
UPDATE clients SET name = 'Пинус Роман Александрович' WHERE id = 'client-xml-10141';
UPDATE clients SET name = 'Константин' WHERE id = 'client-xml-10142';
UPDATE clients SET name = 'Геннадий Овсянников' WHERE id = 'client-xml-10143';
UPDATE clients SET name = 'Левин Сергей Владимирович' WHERE id = 'client-xml-10144';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10145';
UPDATE clients SET name = 'Марат' WHERE id = 'client-xml-10146';
UPDATE clients SET name = 'Николай' WHERE id = 'client-xml-10147';
UPDATE clients SET name = 'Марат' WHERE id = 'client-xml-10148';
UPDATE clients SET name = 'Паршин Никита Владимирович' WHERE id = 'client-xml-10149';
UPDATE clients SET name = 'Клопов Олег Викторович' WHERE id = 'client-xml-10150';
UPDATE clients SET name = 'Ошаров Алексей Геннадьевич' WHERE id = 'client-xml-10152';
UPDATE clients SET name = 'Юрий Пальчиков' WHERE id = 'client-xml-10153';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10154';
UPDATE clients SET name = 'Михаил' WHERE id = 'client-xml-10155';
UPDATE clients SET name = 'Ильдар Рашатович Шамсутдинов' WHERE id = 'client-xml-10156';
UPDATE clients SET name = 'Михаил' WHERE id = 'client-xml-10157';
UPDATE clients SET name = 'Максим' WHERE id = 'client-xml-10158';
UPDATE clients SET name = 'Анатолий' WHERE id = 'client-xml-10159';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10160';
UPDATE clients SET name = 'Безруков Николай Николаевич' WHERE id = 'client-xml-10161';
UPDATE clients SET name = 'Михаил' WHERE id = 'client-xml-10162';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10163';
UPDATE clients SET name = 'РАСТОРГУЕВ ОЛЕГ ВАДИМОВИЧ' WHERE id = 'client-xml-10164';
UPDATE clients SET name = 'Максим Белопотапов' WHERE id = 'client-xml-10165';
UPDATE clients SET name = 'Медведев Илья Александрович' WHERE id = 'client-xml-10166';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10167';
UPDATE clients SET name = 'Клюка Алексей Анатольевич' WHERE id = 'client-xml-10168';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10169';
UPDATE clients SET name = 'Гребнев Лев Борисович' WHERE id = 'client-xml-10170';
UPDATE clients SET name = 'Олег Майборода' WHERE id = 'client-xml-10171';
UPDATE clients SET name = 'Артур' WHERE id = 'client-xml-10172';
UPDATE clients SET name = 'Роман' WHERE id = 'client-xml-10173';
UPDATE clients SET name = 'Лапидус Сергей Геннадьевич' WHERE id = 'client-xml-10174';
UPDATE clients SET name = 'Стрельников' WHERE id = 'client-xml-10175';
UPDATE clients SET name = 'Андрей' WHERE id = 'client-xml-10176';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10177';
UPDATE clients SET name = 'Влад' WHERE id = 'client-xml-10178';
UPDATE clients SET name = 'Евромет Евгений' WHERE id = 'client-xml-10179';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10180';
UPDATE clients SET name = 'Юрий' WHERE id = 'client-xml-10181';
UPDATE clients SET name = 'Григорий' WHERE id = 'client-xml-10182';
UPDATE clients SET name = 'Николай' WHERE id = 'client-xml-10183';
UPDATE clients SET name = 'Виктор' WHERE id = 'client-xml-10184';
UPDATE clients SET name = 'Петр' WHERE id = 'client-xml-10186';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10187';
UPDATE clients SET name = 'Константин' WHERE id = 'client-xml-10188';
UPDATE clients SET name = 'Максим' WHERE id = 'client-xml-10189';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10190';
UPDATE clients SET name = 'Максим' WHERE id = 'client-xml-10191';
UPDATE clients SET name = 'Владимир' WHERE id = 'client-xml-10192';
UPDATE clients SET name = 'Игорь' WHERE id = 'client-xml-10193';
UPDATE clients SET name = 'Евгений' WHERE id = 'client-xml-10194';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10195';
UPDATE clients SET name = 'Гынгазов Максим Геннадьевич' WHERE id = 'client-xml-10197';
UPDATE clients SET name = 'Владислав' WHERE id = 'client-xml-10198';
UPDATE clients SET name = 'Алексей Николаевич' WHERE id = 'client-xml-10199';
UPDATE clients SET name = 'Виталий' WHERE id = 'client-xml-10200';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10201';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10202';
UPDATE clients SET name = 'Павел' WHERE id = 'client-xml-10203';
UPDATE clients SET name = 'Павел' WHERE id = 'client-xml-10204';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10205';
UPDATE clients SET name = 'Сергей Павлович' WHERE id = 'client-xml-10206';
UPDATE clients SET name = 'Гамлет' WHERE id = 'client-xml-10207';
UPDATE clients SET name = 'Максим' WHERE id = 'client-xml-10208';
UPDATE clients SET name = 'Агапчев Алексей Михайлович' WHERE id = 'client-xml-10209';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10210';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10212';
UPDATE clients SET name = 'Андрей' WHERE id = 'client-xml-10213';
UPDATE clients SET name = 'Михаил' WHERE id = 'client-xml-10214';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10215';
UPDATE clients SET name = 'Николай' WHERE id = 'client-xml-10216';
UPDATE clients SET name = 'Максим' WHERE id = 'client-xml-10217';
UPDATE clients SET name = 'Афанасий' WHERE id = 'client-xml-10218';
UPDATE clients SET name = 'Афанасий' WHERE id = 'client-xml-10219';
UPDATE clients SET name = 'Демиденко Юрий' WHERE id = 'client-xml-10220';
UPDATE clients SET name = 'Павел' WHERE id = 'client-xml-10221';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10222';
UPDATE clients SET name = 'Рубановский Сергей Васильевич' WHERE id = 'client-xml-10223';
UPDATE clients SET name = 'Руслан' WHERE id = 'client-xml-10224';
UPDATE clients SET name = 'Марат' WHERE id = 'client-xml-10226';
UPDATE clients SET name = 'Рудольф' WHERE id = 'client-xml-10227';
UPDATE clients SET name = 'Изранцев Алексей' WHERE id = 'client-xml-10228';
UPDATE clients SET name = 'Андрей' WHERE id = 'client-xml-10229';
UPDATE clients SET name = 'Давид' WHERE id = 'client-xml-10230';
UPDATE clients SET name = 'Валентин' WHERE id = 'client-xml-10232';
UPDATE clients SET name = 'Михаил' WHERE id = 'client-xml-10233';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10234';
UPDATE clients SET name = 'Светлана Горюшкина' WHERE id = 'client-xml-10235';
UPDATE clients SET name = 'Роман' WHERE id = 'client-xml-10236';
UPDATE clients SET name = 'Сидоренко Павел' WHERE id = 'client-xml-10237';
UPDATE clients SET name = 'Григорий' WHERE id = 'client-xml-10238';
UPDATE clients SET name = 'Шевченко Антон Геннадьевич' WHERE id = 'client-xml-10239';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10240';
UPDATE clients SET name = 'Марат' WHERE id = 'client-xml-10241';
UPDATE clients SET name = 'Марат' WHERE id = 'client-xml-10242';
UPDATE clients SET name = 'Иван' WHERE id = 'client-xml-10243';
UPDATE clients SET name = 'Михаил' WHERE id = 'client-xml-10244';
UPDATE clients SET name = 'Алексей Зотов' WHERE id = 'client-xml-10245';
UPDATE clients SET name = 'Павел' WHERE id = 'client-xml-10247';
UPDATE clients SET name = 'Леонид' WHERE id = 'client-xml-10248';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10249';
UPDATE clients SET name = 'Вячеслав' WHERE id = 'client-xml-10251';
UPDATE clients SET name = 'Евгений' WHERE id = 'client-xml-10252';
UPDATE clients SET name = 'Алина' WHERE id = 'client-xml-10253';
UPDATE clients SET name = 'Артем' WHERE id = 'client-xml-10254';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10255';
UPDATE clients SET name = 'Волоскова Ольга Николаевна' WHERE id = 'client-xml-10256';
UPDATE clients SET name = 'Тимур Замалтдинов' WHERE id = 'client-xml-10257';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10258';
UPDATE clients SET name = 'Николай' WHERE id = 'client-xml-10259';
UPDATE clients SET name = 'Тарас' WHERE id = 'client-xml-10260';
UPDATE clients SET name = 'Виктор' WHERE id = 'client-xml-10261';
UPDATE clients SET name = 'Владимир' WHERE id = 'client-xml-10262';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10263';
UPDATE clients SET name = 'Размазин Алексей Львович' WHERE id = 'client-xml-10264';
UPDATE clients SET name = 'Наталья' WHERE id = 'client-xml-10267';
UPDATE clients SET name = 'Николай' WHERE id = 'client-xml-10268';
UPDATE clients SET name = 'Олег' WHERE id = 'client-xml-10269';
UPDATE clients SET name = 'Виталий' WHERE id = 'client-xml-10270';
UPDATE clients SET name = 'Рыжкова Екатерина' WHERE id = 'client-xml-10272';
UPDATE clients SET name = 'Константин' WHERE id = 'client-xml-10273';
UPDATE clients SET name = 'Владимир' WHERE id = 'client-xml-10276';
UPDATE clients SET name = 'Андрей Андрияничев' WHERE id = 'client-xml-10277';
UPDATE clients SET name = 'Костя' WHERE id = 'client-xml-10278';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10279';
UPDATE clients SET name = 'Евгений' WHERE id = 'client-xml-10280';
UPDATE clients SET name = 'Вячеслав' WHERE id = 'client-xml-10281';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10282';
UPDATE clients SET name = 'Зураб' WHERE id = 'client-xml-10283';
UPDATE clients SET name = 'Владимир' WHERE id = 'client-xml-10284';
UPDATE clients SET name = 'Зураб' WHERE id = 'client-xml-10285';
UPDATE clients SET name = 'Дмитрий' WHERE id = 'client-xml-10286';
UPDATE clients SET name = 'Алексей Николаевич' WHERE id = 'client-xml-10289';
UPDATE clients SET name = 'Виктор' WHERE id = 'client-xml-10290';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10291';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10292';
UPDATE clients SET name = 'Василий' WHERE id = 'client-xml-10293';
UPDATE clients SET name = 'Батрас' WHERE id = 'client-xml-10294';
UPDATE clients SET name = 'Сергей' WHERE id = 'client-xml-10295';
UPDATE clients SET name = 'Вячеслав' WHERE id = 'client-xml-10296';
UPDATE clients SET name = 'Максим' WHERE id = 'client-xml-10297';
UPDATE clients SET name = 'Изранцев Алексей' WHERE id = 'client-xml-10298';
UPDATE clients SET name = 'Олег Евгеньевич' WHERE id = 'client-xml-10299';
UPDATE clients SET name = 'Игорь' WHERE id = 'client-xml-10300';
UPDATE clients SET name = 'Изранцев Алексей' WHERE id = 'client-xml-10301';
UPDATE clients SET name = 'Максим' WHERE id = 'client-xml-10302';
UPDATE clients SET name = 'Андрей' WHERE id = 'client-xml-10303';
UPDATE clients SET name = 'Изранцев' WHERE id = 'client-xml-10304';
UPDATE clients SET name = 'Алексей' WHERE id = 'client-xml-10305';
UPDATE clients SET name = 'Станислав' WHERE id = 'client-xml-10306';
UPDATE clients SET name = 'Виталий' WHERE id = 'client-xml-10307';
UPDATE clients SET name = 'Адам' WHERE id = 'client-xml-10309';
UPDATE clients SET name = 'Игорь' WHERE id = 'client-xml-10311';
UPDATE clients SET name = 'Константин' WHERE id = 'client-xml-10312';
UPDATE clients SET name = 'Максим Цементум' WHERE id = 'client-xml-10313';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10316';
UPDATE clients SET name = 'Александр' WHERE id = 'client-xml-10317';
UPDATE clients SET name = 'Андрей' WHERE id = 'client-xml-10318';


